### ISSUE TITLE
starting a larch server on windows

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#107]
I am trying get Athena and friends to start a larch server if one is not already running.  On linux, this works by invoking `larch_server start` as a system call early on in the instance of the Demeter program. This, as intended, starts a new server if one is not running.  I then give it a few seconds to get started, then I am off to the races.

On Windows, things don't work.

This works:
```
c:\>python C:\Python27\bin\larch -rc
Serving Larch at port 4966
Registered Functions:
  chdir, cwd, exit, get_data, get_messages, larch, len_messages, ls, wx_update
```
This doesn't:
```
c:\>python C:\Python27\bin\larch_server start
Traceback (most recent call last):
  File "C:\Python27\bin\larch_server", line 88, in <module>
    start_server(port=port, quiet=options.quiet)
  File "C:\Python27\bin\larch_server", line 32, in start_server
    return subprocess.Popen([exe, '-r', '-p', '%d' % port])
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```
Am I naive expecting larch_server to work on Windows?  If so, how is this intended to be done on Windows?

Thanks!

**Comment by newville** [comment]
Hmmm, not sure!   It might require an explicit "X:/Somewhere/Python.exe" as part of the `exe` value (Windows being generally too stupid to try anything like `#!`, relying on registries and other horrors).  I'll try to figure this out, but it may take a couple of days to get to it.

**Comment by bruceravel** [comment]
> (Windows being generally too stupid to try anything like #!, relying on registries and other horrors)

That turns out to be the answer.

In `larch_server`, the call to `subprocess.Popen` treats `C:\Python27\bin\larch` as an executable.

Changing [this line](https://github.com/xraypy/xraylarch/blob/master/bin/larch_server#L32) (and the similar change at line 30) to 
```python
return subprocess.Popen(['python', exe, '-r', '-p', '%d' % port])
```
fixes the problem.

I'll do some testing and submit a PR this afternoon.
