### ISSUE TITLE
feffrunner not available from Python

### ISSUE THREAD

**Issue by Prestipino** [xraypy/xraylarch#127]
Feffrunner is not available when xafs plugin is loaded in Python.
Effectively in the _init_.py  file doesn't import it.
It suppose to work like this or is it a bug??
thanks
Carmelo

**Comment by newville** [comment]
@Prestipino  I'd call that a bug.  should be an easy fix.

**Comment by newville** [comment]
@Prestipino Fixed in 7a10e3bf283f16caef58b9f19ec1ea143583bad7, so that

```
import larch
from larch_plugins.xafs import FeffRunner
```

now works.
