### ISSUE TITLE
autobk parameter XAFS plugins  are lost after function execution?

### ISSUE THREAD

**Issue by Prestipino** [xraypy/xraylarch#128]
Hi
I was wondering why the data group add attributes: pre1 pre2 norm1 norm2 after pre_edge() while 
kmin, kmax , kweight  are not stored.
Maybe will be nice make a dictionary with the parameter of EXAFS extraction in the group.
What do you think about?

**Comment by newville** [comment]
@Prestipino  Ah, good point.  I agree these should be reported.  

Since the names clash with FT parameter names, would it be reasonable to call these kmin_bkg, kmax_bkg, and kweight_bkg to identify them as background-subtraction parameters?   Alternatively, they could go into the "autobk_details" subgroup.  Currently, that's mostly focused on details of the spline fit.

This would be a very simple change, basically adding `group.kmin_bkg = kmin` to the code.   Are you willing/able to make a PR?   That's a good way to make sure you get credit for identifying the problem.

**Comment by bruceravel** [comment]
It's a good point, Carmelo. My vote would be to put them in an "autobk_details" subgroup.

**Comment by Prestipino** [comment]
good for  "autobk_details" subgroup.

On Wed, Feb 17, 2016 at 2:17 PM, Bruce Ravel <notifications@github.com>
wrote:

> It's a good point, Carmelo. My vote would be to put them in an
> "autobk_details" subgroup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xraypy/xraylarch/issues/128#issuecomment-185199838>.
>



-- 
Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959

**Comment by maurov** [comment]
I also would like to express a preference for 'autobk_details' subgroup. Just to better understand, we are talking of a dictionary, right?

**Comment by Prestipino** [comment]
Hi to everybody
I create a subgroup for each of the "extraction" function :
                                                       pre_edge_details ,
autobk_details, xftf, xftr
in which hide of the details
in each subgroup 'function'_details I add an attribute 'params' that
contains the arguments of the function
the idea is store the parameter in a way that can be save it in pythonic
way
the dictionary form  is to make it usable again to call the function for an
another function.
ex.
pre_edge(pippo, **pluto.Pre_edge_details.params)


two questions:


1)which attribute should be keep in parent group   and which move in
details??
pre_edge:
main_group attr
['dmude',
 'e0',
 'edge_step',
 'flat',
 'norm',
 'post_edge',                     # maybe in details?
 'pre_edge',                       # maybe in details?
 'pre_edge_details']


autobk
main group attr.
['autobk_details',
 'bkg',
 'chi',
 'chie',                             # maybe in details?
 'k',
 'pre_edge_details']


2)when are used the default value None for (pre1,norm2,e0) what keep in
param?
I keep the real numerical value for norm2 and pre1
 but for e0 given that a main group attribute also exist  i will keep 'None'
do you have other ideas??


let me know
Carmelo








On Wed, Feb 17, 2016 at 7:09 PM, Mauro Rovezzi <notifications@github.com>
wrote:

> I also would like to express a preference for 'autobk_details' subgroup.
> Just to better understand, we are talking of a dictionary, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xraypy/xraylarch/issues/128#issuecomment-185329325>.
>



-- 
Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959

**Comment by newville** [comment]
@Prestipino thanks for bringing up the discussion!    

For both of your points 1) and 2), and for better provenance in general, maybe each Group that goes through `pre_edge()`, `autobk()`, etc could be given a subgroup (`xafs_details` or better name?) that had all the parameters used in that step, and leave the main group to hold only the data that is expected to really be needed in later steps.    It was sort of obvious that autobk needed this, but maybe every processing step should be expected to have "details" that should be saved for complete documentation.

I think could then also stuff into that subgroup the actual arguments (probably as a dictionary) passed into `pre_edge()`, `autobk()` etc, and so including when `None` or other defaults were taken implicitly.

**Comment by maurov** [comment]
Useful discussion, indeed!

In my experience using Larch functions I have always the need to store all the passed parameters in a nested dictionary (e.g.  self.kwsd = { 'pre_edge' : {'e0' : None,  ...,},  'xftf' : {'xattr' : 'k', ...}}) for later use or for logging.

My preference would then be to store everything in dictionaries. In my (limited) experience with Python, working with dictionaries is much easier than with attributes. I would leave attributes only for methods (= functions) and store variables (= parameters) in a single dictionary. If possible, I would even move the data subgroups (= attributes) to a single dictionary, but you would probably be against it, due to the strong change to introduce in Larch architecture ;)

Anyway, my proposal would be to have in 'Group' two dictionaries: self._params and self._data, then the Larch functions could act and write everything in those dictionaries. This would make things much easier for re-using parameters between functions.

**Comment by newville** [comment]
@maurov  I agree that the arguments to functions are better as dictionaries.  Anybody up for implementing this?

FWIW, it is pretty easy to convert any Group to a dictionary with

```python 
   my_dict = my_group.__dict__
```

and convert most dictionaries to a Group with

```python
   my_group = Group(**my_dict)
```

That's only "most" because dictionary keys can be more general than attribute names (keys might be tuples, numbers, reserved words, or strings with spaces, commas, dots, etc).

**Comment by maurov** [comment]
@newville unfortunately, I do not have time this period for implementing this. Anyway, thanks for the tip for converting Group <-> dict, I overlooked the Group class.

**Comment by Prestipino** [comment]
Hi
I have already done something......... give a look at it.

I would avoid to use massively the dictionaries, they are good for script
but  for the interactive shell are less practical.

I'm sending  a fork xafsplugdetais sorry for the N mistype.

Carmelo



Il 19/feb/2016 18:56, "Mauro Rovezzi" <notifications@github.com> ha scritto:

**Comment by newville** [comment]
@Prestipino  I see a branch was created but don't see any actual changes here.  Do you need to push commits to this branch?

**Comment by Prestipino** [comment]
@Newville Soory conflict between windows interfaces.
commit done

On Sun, Feb 21, 2016 at 5:53 PM, Matt Newville <notifications@github.com>
wrote:

> @Prestipino <https://github.com/Prestipino> I see a branch was created
> but don't see any actual changes here. Do you need to push commits to this
> branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xraypy/xraylarch/issues/128#issuecomment-186856591>.
>



-- 
Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959

**Comment by newville** [comment]
@Prestipino   Thanks -- that looks good.  I think the idea of having each function create a `function_details` group and a dictionary of calling parameters will be really helpful.

I might prefer the name `.pre_edge_details.call_args` to `pre_edge_details.params`, as `params` is sort of over-loaded with meaning, and the intention is to encapsulate the calling arguments.  Does that seem reasonable?

I would sort of prefer the building of the dictionary-of-arguments to be more automated than an `eval()` of a fixed list of names.   That is, this method will work, but will not be so easy to use in other functions.  At this point, don't worry about that, but I might try to change this to be more devious.

I would say make a Pull Request for this branch, after considering renaming `params` to `call_args` or some other name you think might be better.

**Comment by Prestipino** [comment]
@newville
I totally agree for the change of name "params" was the first in my brain
but is often the first.

if you prefer the dictionary could be build by a locals() call just at the
start of the function..

I'll make the modification soon

On Tue, Feb 23, 2016 at 12:28 AM, Matt Newville <notifications@github.com>
wrote:

> @Prestipino <https://github.com/Prestipino> Thanks -- that looks good. I
> think the idea of having each function create a function_details group
> and a dictionary of calling parameters will be really helpful.
>
> I might prefer the name .pre_edge_details.call_args to
> pre_edge_details.params, as params is sort of over-loaded with meaning,
> and the intention is to encapsulate the calling arguments. Does that seem
> reasonable?
>
> I would sort of prefer the building of the dictionary-of-arguments to be
> more automated than an eval() of a fixed list of names. That is, this
> method will work, but will not be so easy to use in other functions. At
> this point, don't worry about that, but I might try to change this to be
> more devious.
>
> I would say make a Pull Request for this branch, after considering
> renaming params to call_args or some other name you think might be better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xraypy/xraylarch/issues/128#issuecomment-187435789>.
>



-- 
Carmelo Prestipino
Sciences Chimiques de Rennes, UMR 6226
Solid State and Materials Chemistry group (CSM)
Campus de Beaulieu, Bât 10B, bureau 123
263 avenue du Général Leclerc
F-35042 RENNES
France
Tel: (+33) 22323 6531
FAX: (+33) 22323 5959
