### ISSUE TITLE
larch server should have a keepalive variable and automatically shutdown 

### ISSUE THREAD

**Issue by newville** [xraypy/xraylarch#136]
In discussion for Demeter https://github.com/bruceravel/demeter/issues/29, the Larch xmlrpc server does not automatically die when a client disconnects.   I think this should be fixed as follows:
1. add a variable `_sys.keep_alive_until` and when the current (unix) timestamp exceeds that, the server will shutdown.  
2. on server startup this will be set 1 day in the future (current time + 86400).
3. on any call to `Server.larch()` or `Server.get_data()`, this will be set 1 day in the future.

For the client shutting down nicely means explicitly executing "Server.exit()", same as now.
But, to keep a still-running-but-not-currently-in-use session alive, the client (say, Athena) would need to periodically get some data, just to keep communication alive and prevent the server from stopping itself.
We could add a `Server.keep_alive()` command.

Other suggestions welcome. I'm not in a rush for this, and we should probably coordinate with demeter.

**Comment by newville** [comment]
@bruceravel  Provisionally, I set the xmlrpc server to automatically exit after 3 days of inactivity with commit 73d997c8c1973c41fd51486adb5df90d86b3a80e .   Comments, suggestions still sought!

**Comment by bruceravel** [comment]
3 days is fine by me.  Honestly, I have not thought about this, so I might change my mind at some point....

**Comment by newville** [comment]
@bruceravel I think the best thing would be for athena/artemis to essentially ping the server by asking for some (any!) data periodically (say, once per hour).   That will keep the server alive if the GUI is idle, but also allow the server to stop if the GUI stops making request.  I think that athena/artemis already have auto-save-projects.... that would probably ping the larch server anyway.

The question is really how long the "idle but still in use" timeout should be.  One hour is clearly too short, one week is clearly too long.  I'd guess that "overnight" would be OK.

**Comment by newville** [comment]
this is now implemented....
