### ISSUE TITLE
Running larch in an anaconda python environment

### ISSUE THREAD

**Issue by JPHammonds** [xraypy/xraylarch#153]
I am just starting to look at larch in prep for a meeting and tried installing larch in an anaconda environment (http://conda.pydata.org/docs/using/envs.html).  I have encountered issues before running wx in an environment, there is an issue with the way the wrapping is done.  I have been able to get around this in the past by running pythonw instead of python.  I tried making the change in the larch script but this failed.  Running as installed in an environment I get:

(larch) Defiant:bin hammonds$ larch
========================================================================
Larch 0.9.30 (18-Aug-2016) M. Newville and Larch Development Team
Using Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)],
Numpy 1.11.2, scipy 0.18.1, matplotlib 1.5.3, and wxpython 3.0.0.0
========================================================================

This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

**Comment by JPHammonds** [comment]
Note I can get 
larch --nowx 

to work

**Comment by newville** [comment]
@JPHammonds  Yes, this "need pythonw with Anaconda + wxPython on Mac OSX" is a known, irritating issue.   I, and others, have complained and pointed out that all other Pythons on Mac OSX solved this problem 10 years ago (even the Macports version of Python works!)   Continuum seems to be unwilling to make a Framework build, which is apparently needed for wxPython.

Installing from source with "python setup.py install" will fix this issue, replacing the "#!" line.  Also, the `larch_makeicons` program will create a desktop folder called Larch containing Apps that do run correctly.

**Comment by JPHammonds** [comment]
This still does not work in running in an Anaconda Environment.  The scripts created assume python in ~/anaconda/bin.  For an environment it is in ~/anaconda/envs/envName

where envName is the name of the created environment.


On Nov 28, 2016, at 3:37 PM, Matt Newville <notifications@github.com<mailto:notifications@github.com>> wrote:


@JPHammonds<https://github.com/JPHammonds> Yes, this "need pythonw with Anaconda + wxPython on Mac OSX" is a known, irritating issue. I, and others, have complained and pointed out that all other Pythons on Mac OSX solved this problem 10 years ago (even the Macports version of Python works!) Continuum seems to be unwilling to make a Framework build, which is apparently needed for wxPython.

Installing from source with "python setup.py install" will fix this issue, replacing the "#!" line. Also, the larch_makeicons program will create a desktop folder called Larch containing Apps that do run correctly.

**Comment by JPHammonds** [comment]
I have modified the script that gets creates under Desktop/Larch/{LarchApp}/Contents/MacOS/

so that PYBIN ends up pointing to the environment’s version of python.  Earlier in the larch_makeicons script
root is defined by:



root = sys.exec_prefix

This is the value that is needed for the PYBIN.  Is it possible to set it equal to this and not go through
the checks in mac_script_header?

**Comment by newville** [comment]
@JPHammonds  Ah, yes, good point about effectively hard-coding in the root environment.   

I'm not 100% certain of the *right* behavior here: maybe larch should always create its own environment, install into that, and have the Apps switch to the proper environment. 

I guess I usually use environments as a debugging aide, but then expect things to stabilize to the root environment.  But, using an environment for deployment might be useful.

**Comment by JPHammonds** [comment]
I err on  leaving that kind of decision (installing to an environmen) to the user but I often expect too much from the user.  In any event, it would be nice to make it work.

On Nov 28, 2016 5:47 PM, Matt Newville <notifications@github.com> wrote:

@JPHammonds<https://github.com/JPHammonds> Ah, yes, good point about effectively hard-coding in the root environment.

I'm not 100% certain of the right behavior here: maybe larch should always create its own environment, install into that, and have the Apps switch to the proper environment.

I guess I usually use environments as a debugging aide, but then expect things to stabilize to the root environment. But, using an environment for deployment might be useful.

**Comment by maurov** [comment]
@JPHammonds @newville I think this issue is fixed with the current version of the installers. If not, please, feel free to reopen it.
