### ISSUE TITLE
from PyFAI.calibration import Calibration breaks larch CLI, PyQt v Wx eventloop

### ISSUE THREAD

**Issue by newville** [xraypy/xraylarch#157]
I noticed that the larch command-line program wasn't responding well to wx windows (plots, etc), and tracked this down to the use of 
```python
from PyFAI.calibration import Calibration
```
which I believe import PyQt, which seems to mess up the hack of the command-line event loop to allow smooth wx interaction (at least on Mac OSX).  FWIW, the import of pyFAI and pyFAI.calibrant seem fine.

I believe the `Calibration` module / GUI isn't used anyway -- it was commented out from mapviewer and doesn't seem to be used in diFFit....  Can these imports be removed?

**Comment by margaretkolbeannellen** [comment]
This should be completely removed from modules/GUI. It is not used.
