### ISSUE TITLE
small error in setup.py requirements lists

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#159]
At https://github.com/xraypy/xraylarch/blob/master/setup.py#L19, `requests` is listed as being a requirement for larch's XRD functionality.  It should be listed in `required_modules` instead as it is used outside of the XRD functionality.

I found that, after a `git pull`, larch was non-functional until I used pip to install `requests`.

**Comment by newville** [comment]
@bruceravel @margaretkolbeannellen  OK, will do.   Even if it is really only used in the XRD code, it's an easy enough dependency to meet.

**Comment by newville** [comment]
fixed.
