### ISSUE TITLE
awkward read_ascii behavior

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#161]
I know that there are many more interesting things to do with Larch than read column ascii files.  That said, I have really been pounding on that particular function this week.

Suppose you have a file like this:

```
# comment
# comment
# ---------------
# weird_label  weirder_label  all  the  rest  are  ok
  1.0 2.0 3.0 4.0 5.0 6.0 7.0
  1.1 2.1 3.1 4.1 5.1 6.1 7.1
... etc
```
Doing
```
larch> a=read_ascii('file', labels="a b")
```
results in something like
```
Traceback (most recent calls last): 
   File <stdin>, line 1
    a=read_ascii('file', labels="a b")
  ^^^
   File <stdin>, line 1
  File "/usr/share/larch/plugins/io/columnfile.py", line 202, in read_ascii
    _labels.append("col%" % (i+1))

ValueError: incomplete format
```
which seems like the wrong behavior.

My point is that it seems like specifying fewer than the total number of column labels should default to something like `a b col3 col4 etc...` or use existing column labels.  That is, specifying a subset of the labels does not seem like it should be user error.

**Comment by newville** [comment]
Will fix.

**Comment by newville** [comment]
Should be fixed in master now, so that it produces 'weird_label', ..., 'ok', 'col8', 'col9', ....

**Comment by newville** [comment]
I think this is now resolved....
