### ISSUE TITLE
plot not working with recent wxpython

### ISSUE THREAD

**Issue by jn287** [xraypy/xraylarch#162]
The plot command in larch is not working for me with recent development releases of wxpython. It was working fine with wxpython 3.0.2, so I guess I can fix this by downgrading.

```
$ larch
WARNING: Not using BLAS, PCA calculation will be slower
WARNING: Not using BLAS/ATLAS, PCA calculation will be slower
========================================================================
Larch 0.9.32 (2016-Dec-20) M. Newville and Larch Development Team
Using Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609],
Numpy 1.11.0, scipy 0.17.0, matplotlib 1.5.1, and wxpython 3.0.3.dev2749+f803d20
========================================================================

larch> x = range(1,5)
larch> y = range(1,5)
larch> plot(x,y)
Traceback (most recent calls last): 
   File <stdin>, line 1
    plot(x,y)
   File <stdin>, line 1
  File "/usr/local/lib/python2.7/dist-packages/larch/larchlib.py", line 611, in wrapper
    return fcn(*args, **keywords)
  File "/usr/share/larch/plugins/wx/plotter.py", line 353, in _plot
    wintitle=wintitle,  _larch=_larch)
  File "/usr/local/lib/python2.7/dist-packages/larch/larchlib.py", line 611, in wrapper
    return fcn(*args, **keywords)
  File "/usr/share/larch/plugins/wx/plotter.py", line 234, in _getDisplay
    display = creator(window=win, wxparent=wxparent, size=size, _larch=_larch)
  File "/usr/share/larch/plugins/wx/plotter.py", line 115, in __init__
    exit_callback=self.onExit, **kws)
  File "build/bdist.linux-x86_64/egg/wxmplot/plotframe.py", line 21, in __init__
    self.BuildFrame()
  File "build/bdist.linux-x86_64/egg/wxmplot/baseframe.py", line 131, in BuildFrame
    sbar = self.CreateStatusBar(2, wx.CAPTION|wx.THICK_FRAME)

AttributeError: 'module' object has no attribute 'THICK_FRAME'
larch>
```

**Comment by newville** [comment]
@jn287 Sorry for the trouble.  I think you might be able to solve this by updating wxmplot.  
Please let us know how that goes.

**Comment by jn287** [comment]
I've updated to wxmplot 0.9.23 but I still have the same issue

**Comment by newville** [comment]
@jn287   Hm, you say "I still have the same issue" and give no other information.  So I have to assume you get exactly the same message.     

That suggests that wxmplot may not have actually been upgraded (as THICK_FRAME is not in the code for wxmplot 0.9.23) or that some earlier version of wxmplot is still being used.   The "build/bdist.linux-x86_64/egg/wxmplot/baseframe.py" implies one of the "wxmplot...egg..." is being used -- those are nasty little creatures.  I'd suggest explicitly deleting any of the installed instances of wxmplot and then trying to reinstall wxmplot.

**Comment by jn287** [comment]
Yes, there was an old version of wxmplot installed and I think this was the cause of my problems. After uninstalling all versions of wxmplot and reinstalling the latest version things seem to be working as they should. Thanks for helping me sorting this out.

**Comment by newville** [comment]
@jn287 Great!   I'll look into what we can do anything to make sure the new version is always used.
