### ISSUE TITLE
How to use save/restore

### ISSUE THREAD

**Issue by jn287** [xraypy/xraylarch#163]
I have some problems figuring out how to use using the save/restore functions. I can save individual variables and then restore them:

```
larch> g = group()
larch> g.a = 3
larch> g.b = 5
larch> save('save', g.a, g.b)
larch> h = restore('save')
larch> show h
== Group 0x7fc8c810e790: 0 methods, 2 attributes ==
  a: 3
  b: 5
larch> 
```
Is it possible to save an entire group without specifying each individual variable to save? I tried doing it like this but I get an error:

```
larch> save('save', g)
Traceback (most recent calls last): 
   File <stdin>, line 1
    save('save', g)
   File <stdin>, line 1
  File "/usr/local/lib/python2.7/dist-packages/larch/larchlib.py", line 611, in wrapper
    return fcn(*args, **keywords)
  File "/usr/share/larch/plugins/io/save_restore.py", line 135, in save
    saver.save(*args)
  File "/usr/share/larch/plugins/io/save_restore.py", line 109, in save
    self.add_data(self.fh, nam, obj)
  File "/usr/share/larch/plugins/io/save_restore.py", line 71, in add_data
    name = fix_varname(name)

TypeError: 'str' object does not support item assignment
larch> 
```

**Comment by newville** [comment]
@jn287 Ah, good point, and sorry for the trouble.   save()/restore() is sort of hobbled by using hdf5.  It should be using JSON.  Will fix soon, but maybe not today.

**Comment by jn287** [comment]
Ok, good to know. I'm not working with huge data sets so I can use numpy's savetxt to save the data I need, but an easy to use save/restore feature would be a good addition to larch.

**Comment by newville** [comment]
@jn287  I think that save()/restore() are now much, much better at saving complex objects, and now use json for storage instead of HDF5.

**Comment by newville** [comment]
@jn287  I think this is resolved in the master branch, if not in a release.  Please open a new issue if you're still having trouble with save() / restore()
