### ISSUE TITLE
startup error messages

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#179]
Here are some startup errors:

```
bruce@titanium [cifdb](master) > larch
  File "/usr/local/lib/python2.7/dist-packages/larch/builtins.py", line 345, in _plugin_file
    out = imp.load_module(plugin, fh, modpath, desc)
  File "/usr/share/larch/plugins/diFFit/cifdb.py", line 42, in <module>
    from larch_plugins.math import as_ndarray
Python Error at plugin '/usr/share/larch/plugins/diFFit/cifdb.py', line 0
   ^
ImportError: cannot import name as_ndarray
  File "/usr/local/lib/python2.7/dist-packages/larch/builtins.py", line 345, in _plugin_file
    out = imp.load_module(plugin, fh, modpath, desc)
  File "/usr/share/larch/plugins/wx/xrddisplay.py", line 63, in <module>
    from larch_plugins.math import index_of
Python Error at plugin '/usr/share/larch/plugins/wx/xrddisplay.py', line 0
   ^
ImportError: cannot import name index_of
==============================================================================
Larch 0.9.33 (2017-Apr-3) M. Newville, M. Koker, B. Ravel, and others
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609],
numpy 1.12.1, scipy 0.19.0, matplotlib 1.5.1, wxpython 3.0.2.0
==============================================================================
```

The first one was resolved by editing line 42 of `/usr/share/larch/plugins/diFFit/cifdb.py` to read
```python
from larch.utils import as_ndarray
```
instead of
```python
from larch_plugins.math import as_ndarray
```
I don't quite understand how the file `/usr/share/larch/plugins/diFFit/cifdb.py` gets built.  It seems to be processed from something under `plugins/difFFit/`, but not in a way that is clear to me.

The similar change in `/usr/share/larch/plugins/wx/xrddisplay.py` seemed to work.  There seems to be some confusion in how @margaretkolbeannellen imports things from the math utilities plugin.  (Or something broken on my computer, I suppose....)

At this point, I see this upon start-up:
```
bruce@titanium [xraylarch](master) > larch
  File "/usr/local/lib/python2.7/dist-packages/larch/builtins.py", line 345, in _plugin_file
    out = imp.load_module(plugin, fh, modpath, desc)
  File "/usr/share/larch/plugins/wx/xrddisplay.py", line 65, in <module>
    from larch_plugins.xrd import calc_q_to_d,calc_q_to_2th,calc_d_to_q,calc_2th_to_q
Python Error at plugin '/usr/share/larch/plugins/wx/xrddisplay.py', line 0
   ^
ImportError: cannot import name calc_q_to_d
==============================================================================
Larch 0.9.33 (2017-Apr-3) M. Newville, M. Koker, B. Ravel, and others
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609],
numpy 1.12.1, scipy 0.19.0, matplotlib 1.5.1, wxpython 3.0.2.0
==============================================================================
```
This stumps me.  When I ack for the string `calc_q_to_d` in the build directory, I don't get a hit.  When I ack for that string in ` /usr/share/larch/`, it is found in `plugins/diFFit/XRDCalculations.py`, which seems to be a generated file.  And I guess I don't really understand how plugin access is implemented in Larch.

HTH,
B

**Comment by margaretkolbeannellen** [comment]
Bruce,

This error results from an older version of the code already exisiting in your path. If you start by removing/deleting the installed larch plugins directory (should be /usr/share/larch/plugins/ for you), and then perform an install, this error will go away. An out of date version of the script is creating the trouble.

Best,
margaret

**Comment by bruceravel** [comment]
Thanks Margaret.
