### ISSUE TITLE
python ./setup.py build text is misleading

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#226]
Matt, 

When you do `python ./setup.py build`, you might be told something like this:

```
#==============================================================#
#=== Warning: Some recommended Python Packages are missing:
     pyFAI:  needed for xrd modules
     CifFile:  needed for xrd modules
     fabio:  needed for xrd modules
     tomopy:  needed for tomography modules
     scikit-image:  needed for tomography modules
     epics:  needed for using the EPICS control system

Some functionality will not work until these are installed.
See INSTALL for further information.
#==============================================================#
```
The name of the pip package that provides CifFile.py is `PyCifRW`. 

I would suggest that the warning text specify package names rather than module names.

Disclamer: I use pip for these things.  Could be different with other package managers (anaconda or what-not).

**Comment by newville** [comment]
@bruceravel  Good point.   This is a "module vs package" issue, but we should fix these.   That is the package is named "PyCifRW" (and "pyepics") and that's what you would tell 'pip install', but the module is name "CifFile" (and "epics") which is what you tell "import". 

I'll fix this.

**Comment by newville** [comment]
I think these are now (in master branch, that is) better,

**Comment by newville** [comment]
this is now much better in 0.9.37
