### ISSUE TITLE
xafs_plots from module to plug-in?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#237]
Hello,

I was wondering if we could move the current `xafs_plots` module (= a set of functions written in Larch DSL) to a plug-in (= a set of functions written in pure python and then exposed to Larch).

Personally, I would prefer having in Larch only plug-ins. Please, could you give me your point of having both?

Thanks,
Mauro

**Comment by newville** [comment]
@maurov OK, I'll try to do that.   For me, it was just easier to do it as a module, and these grew out of many of the example scripts for XAFS processing.   But having available in Python is a fine idea.

**Comment by maurov** [comment]
@newville it's great to know you are not against this idea and I see you have already done it, thank you very much indeed!

**Comment by newville** [comment]
@maurov Thanks -- yeah, I think it is better to have these as python too.
