### ISSUE TITLE
use silx for specfile support

### ISSUE THREAD

**Issue by newville** [xraypy/xraylarch#239]
@maurov I suggest we use silx for its SpecFile reader.   That is, I think we could add silx as a dependency and so be able to support spec files on all platforms.  

I haven't looked in detail -- is there more to it than just changing the import statement?

**Comment by maurov** [comment]
@newville I fully agree including the [ `silx` library](https://github.com/silx-kit/silx) as a dependency in Larch plugins in general and in particular for the SPEC file reader. In fact, also PyMca will be based on SILX in the future.

Seen the recent activity on the ifeffit mailing list, I already had on my **todo** list a full refresh of the SpecFile plugin by moving [my current version in `sloth`](https://github.com/maurov/xraysloth/tree/master/sloth/io) to Larch.

I propose to take care of this and make a pull request by next week. If I find some extra time, I will include also the documentation, examples and tests. Do you have a preference where to include examples and tests files for plugins? In the main directory (as it is currently) or within the plugin directory?

**Comment by newville** [comment]
@maurov Great --   I'm glad you agree.  Pulling in more visualization tools for specfiles would be really useful too.
