### ISSUE TITLE
Proposal for an informal Larch code camp during XAFS17 conference

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#244]
Would anybody be interested in having a sort of informal Larch code camp during next [XAFS17 conference](http://www.xafs2018.com/)? The conference program being very dense (workshops starting already on Sunday!) I do not think we will have the time to code that much, but it could be a good occasion to discuss/share design guidelines and library roadmap.

Any feedback (positive/negative) on this proposal is welcome.

**Comment by newville** [comment]
@maurov  Yes, I think this would be a great idea.  I'm not sure how many of would actually show up, which might make it somewhat informal.  I'll look into this....

**Comment by maurov** [comment]
From the [ICALEPS2017 proceedings](http://accelconf.web.cern.ch/AccelConf/icalepcs2017/index.html), I have read about the [ParSeq project](http://accelconf.web.cern.ch/AccelConf/icalepcs2017/doi/JACoW-ICALEPCS2017-THPHA186.html). A Python/Qt data analysis environment developed at Balder beamline of MAX IV. I hope they could join the discussion too...

**Comment by orbitalz** [comment]
I am just a beginner user of Larch and have a little bit Python knowledge. However, I am interested in the camp. It could give me a boost how to use larch, the principle of Larch algorithm etc. I wonder if I could join such the event?

**Comment by orbitalz** [comment]
Thank you so much for the suggestion.

**Comment by newville** [comment]
Just to let everyone who is reading here know:   it looks like a workshop/meeting will happen at XAFS17, hopefully with a room for up to 20 people.  We're still waiting to here final details on the room, and Mauro and I are working on ideas for the content.   The idea is *not* to be an EXAFS tutorial, but a discussion of Larch + Python Apps for XAFS++.   If anyone is interested in participating, let me or Mauro know either here or by email.  We're hoping to send out a wider announcement (say on ifeffit mailing list) in a few weeks.

**Comment by orbitalz** [comment]
Is it intended for the potential user who is going to use LARCH on their python scripts?

**Comment by newville** [comment]
@orbitalz  Yes, I think so.  The idea is to be a meeting of people interesting in using Larch and/or Python in scripting/programming context, and of course related to XAFS-like things.  We will try to avoid "how to analyze XAFS data with Larch" tutorial, and be more focused on "how to use Larch in scripting" and maybe even discuss related/competing Python libraries....
