### ISSUE TITLE
save_config in JSON or yaml hard dependency

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#246]
If `yaml` is not installed, the `xasgui` plugin will not close correctly because `save_config()` (from `larchlib`) will generate a `RuntimeError`.

I think the best would be saving the configuration via JSON, otherwise `yaml` could be made hard dependency at setup.

**Comment by newville** [comment]
@maurov Will fix.

**Comment by newville** [comment]
yaml is now a requirement.
