### ISSUE TITLE
`--root="${pkgdir}"` ignored at some places in `setup.py install`

### ISSUE THREAD

**Issue by deep-42-thought** [xraypy/xraylarch#247]
The packaging step of xraylarch fails on archlinux since version 0.9.38 (0.9.37 worked fine, 0.9.39 still fails) with:

```
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 311, in <module>
    shutil.copy(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/bin/larch_server'
==> ERROR: A failure occurred in package().
```

The command executed (as non-root) is:
```
python2 setup.py install --skip-build --root="${pkgdir}" --prefix=/usr
```

My guess is, that `--root=...` is not honored in all places, thus `/usr/bin/larch_server` gets touched instead of `${pkgdir}/usr/bin/larch_server`

regards,
Erich

**Comment by deep-42-thought** [comment]
this patch fixes the issue for me, but is not tested without --root and might not repair other places, where the --root is being ignored, too:
```
--- a/setup.py	2018-07-10 16:33:03.044849216 +0200
+++ b/setup.py	2018-07-10 16:32:51.198144418 +0200
@@ -197,7 +197,7 @@
     requirements = f.readlines()
 
 # now we have all the data files, so we can run setup
-setup(name = 'xraylarch',
+dist = setup(name = 'xraylarch',
       version = __version__,
       author = 'Matthew Newville and the X-rayLarch Development Team',
       author_email = 'newville@cars.uchicago.edu',
@@ -215,6 +215,7 @@
                    'Programming Language :: Python',
                    'Topic :: Scientific/Engineering'],
      )
+icmd = dist.get_command_obj('install')
 
 
 def remove_cruft(basedir, filelist):
@@ -307,7 +308,7 @@
     scriptdir = pjoin(sys.exec_prefix, bindir)
     for src in scripts:
         _, fname = psplit(src)
-        dest = pjoin(scriptdir, fname)
+        dest = pjoin(icmd.root + scriptdir, fname)
         shutil.copy(src, dest)
         os.chmod(dest, 493) # mode=755
 
```

**Comment by newville** [comment]
@deep-42-thought Ah, yes I can see that non-Anaconda non-root environments might have a problem with the new explicit installation of scripts.   That is, scripts such as larch_server are now explicitly installed instead of being installed as part of the "package data", as this hid them inside the setuptools egg file, which we do not normally we want -- we want those scripts installed in a place where the system can find them as runnable programs/scripts.

For a non-root install, it is not always clear where the runnable scripts and binaries are expected to go.    But, your patch looks like a good approach.

**Comment by newville** [comment]
@deep-42-thought I sort of followed your patch.  I'm slightly reluctant to say this is "fixed" as I have no doubt it could be broken with other combinations of options to setuptools.

I'm somewhat sympathetic, but not exactly excited about trying to support non-standard installs.  It is way better and recommended to use a virtual environment and/or a special purpose install of Anaconda Python.  If you (or anyone) wants to do something else, you have to accept some responsibility for installing it.

**Comment by deep-42-thought** [comment]
Your fix does not work, because it seems pjoin ignores the first argument if the second one is a full path (which it is).
btw: I would not exactly call the --root=... approach a non-standard install - I've looked into archlinux's package sources and the majority of python-* packages there is built and packaged exactly this way.

**Comment by newville** [comment]
@deep-42-thought  Hm,  OK.   A patch or PR that doesn't break current usage and makes it work for your use case is welcome. 

I do not find "what archlinux does" to be a very compelling definition of "standard install" ;).  We're trying to get a fairly large set of python libraries and programs to end users, most of whom are not python programmers.  We recommend and support using Anaconda Python, and generally discourage people from installing this (or any other scientific python package!) into the system Python.

We use setuptools for python packaging, but this project definitely hits all the warts of Python packaging and setuptools.   The PyPI package is out-of-date, and we do not have wheels.   

Python programmers *can* use `python setup.py install`, but I have no doubt that this could be broken with some non-standard (yes) options such as setting `--root`.   Installing as a system package on archlinux is not a priority for me, but if you're interested in trying to fix this or anything else, that would be great.

**Comment by deep-42-thought** [comment]
Ok, I understand, that a packaging environment is not your primary target of end-user and I'm willing to help :)
This patch sets up the correct `scriptdir` for me:
```
--- xraylarch-0.9.40/setup.py	2018-07-17 19:59:54.073741303 +0200
+++ xraylarch-0.9.40/setup.py	2018-07-17 19:59:54.073741303 +0200
@@ -308,7 +308,7 @@
     scriptdir = pjoin(sys.exec_prefix, bindir)
     install_prefix = _setup.get_command_obj('install').root
     if install_prefix is not None:
-        scriptdir = pjoin(install_prefix, scriptdir)
+        scriptdir = install_prefix + scriptdir
 
     for src in scripts:
         _, fname = psplit(src)
```
Thanks for taking the time to solve this.
Regards,
Erich

**Comment by newville** [comment]
On Tue, Jul 17, 2018 at 1:08 PM deep-42-thought <notifications@github.com>
wrote:

> Ok, I understand, that a packaging environment is not your primary target
> of end-user and I'm willing to help :)
> This patch sets up the correct scriptdir for me:
>
> --- xraylarch-0.9.40/setup.py	2018-07-17 19:59:54.073741303 +0200
> +++ xraylarch-0.9.40/setup.py	2018-07-17 19:59:54.073741303 +0200
> @@ -308,7 +308,7 @@
>      scriptdir = pjoin(sys.exec_prefix, bindir)
>      install_prefix = _setup.get_command_obj('install').root
>      if install_prefix is not None:
> -        scriptdir = pjoin(install_prefix, scriptdir)
> +        scriptdir = install_prefix + scriptdir
>
>      for src in scripts:
>          _, fname = psplit(src)
>
>
​Err, using `os.path.join` (assigned  to `pjoin` here) is almost certainly
required for most OSes. ​

You probably need to figure out how
`_setup.get_command_obj('install').root` interacts with `sys.prefix`, or
somehow determine the absolute path of that `install_prefix`.  It would be
nice if that worked with virtual environments.

For sure, first, do no harm.​  The whole business of using the output of
`setuptools.setup()` seems fragile to me.

**Comment by deep-42-thought** [comment]
`os.path.join` most certainly does the wrong thing:
```
>>> import os
>>> os.path.join("/test","/bla")
'/bla'
```

**Comment by deep-42-thought** [comment]
see for example: https://stackoverflow.com/questions/1945920/why-doesnt-os-path-join-work-in-this-case

**Comment by newville** [comment]
@deep-42-thought 
>  os.path.join most certainly does the wrong thing

That is a really odd view.  We're using os.path.join.

You will need to figure out a different way to combine the return of `setup()` and `sys.prefix` to determine whereto install the scripts.   It may be that setuptools has another way of installing console applications that is both cross-platform and handles setting `--root`.

**Comment by deep-42-thought** [comment]
What exactly is your concern with not-using `os.path.join`? - It seems to be impossible to cleanly prepend something to an absolute path with it.

**Comment by newville** [comment]
> The use case for --root is packaging: you build the software and "install" it in some empty
> directory which then gets archived into the package and then installed on the target machine on /.

I'm afraid that other things we do in `setup.py` will break this model, beyond determining the absolute paths for installing runnable scripts.

> Changing sys.prefix is different: This will also make the scripts be aware of the different root
>  (imagine some script calling some executable by absolute path) - this is not what we want
> (and this is also the reason why there is --root in setuptools.

I did not mean to imply that you should change `sys.prefix`.  Instead, you should replace it.   

> How about scriptdir = os.path.normpath(install_prefix + os.sep + scriptdir)? This should be portable.

No, this will not work: 
```
    >>> os.normpath('foo' + os.sep + sys.prefix)
    'foo\\C:\\Users\\newville\\AppData\\Local\\Continuum\\anaconda3'
```

The documentation for `os` clearly states to use `os.path.join` instead of concatenating strings with `os.sep`.  Joining  paths in `setup.py` will use `os.path.join`. 

> Btw: I think the root cause is, that scripts need to be installed outside of setuptools at all - because
> setuptools would have all the switches and options available and implemented portably. IMHO it
>  would be cleaner to let setuptools handle all the installing.

Well, we install a lot of data files including executable scripts, and do other things outside setuptools such as repairing RPATH inside shared libraries on MacOS and Linux and making desktop icons on MacOS and Windows.

If we use the simplest way of installing executable scripts as data files with setuptools, it places thes scripts *inside* the egg file, where they are not readily accessible.

Now, it may very well be that some of these tasks could be handled by `setuptools` and that we're not using that package very well.  It has not been that long since we switched from using distutils.   A more comprehensive set changes to `setup.py` might be worth exploring.  In fact, I doubt that your approach of hacking the installation path for scripts to use `--root` is likely to work without such a more comprehensive change to `setup.py`.
