### ISSUE TITLE
Diffkk gives NameError: name 'Interpreter' is not defined

### ISSUE THREAD

**Issue by jcesardasilva** [xraypy/xraylarch#257]
I tried to repeat the example in https://xraypy.github.io/xraylarch/xafs/diffkk.html, which is 

```
print 'Reading copper foil data'
data=read_ascii('../xafsdata/cu_10k.xmu')
dkk=diffkk(data.energy, data.mu, z=29, edge='K', mback_kws={'e0':8979, 'order':4})

print 'Doing diff KK transform'
dkk.kk()

newplot(dkk.energy, dkk.f2, label='f2', xlabel='Energy (eV)', ylabel='scattering factors',
        show_legend=True, legend_loc='lr')
plot(dkk.energy, dkk.fpp, label='f"(E)')
plot(dkk.energy, dkk.f1,  label='f1')
plot(dkk.energy, dkk.fp,  label='f\'(E)')
```
but it does not work and give

```
In [6]: dkk = larch.xafs.diffkk(data.energy,data.mu, z=29,edge='K',mback_kws={'e
   ...: 0':8979, 'order':4})                                                    
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-17f9f32182fd> in <module>
----> 1 dkk = larch.xafs.diffkk(data.energy,data.mu, z=29,edge='K',mback_kws={'e0':8979, 'order':4})

/usr/local/lib/python3.7/site-packages/larch/xafs/diffkk.py in diffkk(energy, mu, z, edge, mback_kws, _larch, **kws)
    319         mback_kws:  arguments for the mback algorithm
    320     """
--> 321     return diffKKGroup(energy=energy, mu=mu, z=z, mback_kws=mback_kws, _larch=_larch)

/usr/local/lib/python3.7/site-packages/larch/xafs/diffkk.py in __init__(self, energy, mu, z, edge, mback_kws, _larch, **kws)
    217 
    218         if _larch == None:
--> 219             self._larch   = Interpreter()
    220         else:
    221             self._larch = _larch

NameError: name 'Interpreter' is not defined
```
From where I can get "Interpreter"?

**Comment by newville** [comment]
@jcesardasilva Sorry for the trouble...  it should not need an Interpreter, but I'll look into it.

**Comment by newville** [comment]
@jcesardasilva fixed in git master so that for me:


    Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from larch.xafs import diffkk 
    >>> from larch.io import read_ascii
    >>> data = read_ascii('../xafsdata/cu_10k.xmu')
    >>> dkk = diffkk(data.energy, data.mu, z=29, edge='K', mback_kws={'e0':8979, 'order':3})
    >>> dkk.kk()
    8979

    >>> import  wxmplot.interactive as wi
    >>> wi.plot(dkk.energy, dkk.fp, label="$f'(E)$", title='DIFFKK Cu', xlabel='Energy (eV)')
    >>> wi.plot(dkk.energy, dkk.fpp, label="$f''(E)$")

which should work from either Python shell or Jupyter

**Comment by newville** [comment]
fixed, and closing
