### ISSUE TITLE
feffrunner does not get endswith('exe')

### ISSUE THREAD

**Issue by erdzeichen** [xraypy/xraylarch#259]
Heyho, I found a bug in the larch that stops the running of feff.

In feffrunner.py line 16 the condition
 if uname == 'win' and exename.endswith('.exe'):
is never met since the exename.endswith('.exe') is never set before. due to this the program does not find the execuatbles and never runs feff

**Comment by newville** [comment]
@erdzeichen Thanks!  That looks like it should be 

    if uname == 'win' and not exename.endswith('.exe'): 
         exename = "%s.exe" % exename

this is now fixed in the master version.  Please test if you can (I'll run this on Windows tomorrow).

**Comment by maurov** [comment]
@newville I assume this is fixed

**Comment by newville** [comment]
@maurov yes, thanks (and for closing the other resolved issues!)
