### ISSUE TITLE
XAS gui energy/kscale

### ISSUE THREAD

**Issue by erdzeichen** [xraypy/xraylarch#260]
Hej,
there is a bug in the EXAFS rider of the XAS viewer. The energy scale stays in eV if I swithc from chi(E) to anything in k or r space. IF I kill the plot window and then create a new one the behaviour is normal (workaround)
Best
Jens

**Comment by newville** [comment]
@erdzeichen Hm, I don't see that. at least not with a simple example data file with as-released 0.9.46 or with the latest master version.    

If this is something you always see can you verify the version of Larch and OS you're using and maybe send a data file (plain text, zip, or project file)?

**Comment by erdzeichen** [comment]
Hi Matt,
I got this when I plot something in the normalization tab and then change to the EXAFS tab. Updating to the newest Larch fixed the problem, sorry for not checking this earlier. 
Anyhow, its a nice tool and I'm currently working with it in python and have converted all my people to it. Have a nice weekend
Jens

**Comment by newville** [comment]
@erdzeichen OK great - that was easy ;).
