### ISSUE TITLE
For loops for reading files from Athena Project File

### ISSUE THREAD

**Issue by killiantallman** [xraypy/xraylarch#264]
I am trying to write my script to have the functionality of just specifying the Athena Project File and then looping over the files contained in the project to plot and eventually fit. I have gotten only this far as I could not find any good examples on the website on how to do this properly:
```
cell5_Ni = read_athena('path/file.prj')

for file in group2dict(cell5_Ni):
    data = extract_athenagroup(cell5_Ni.file)
    show(data,'\n')
    print(data,'\n')
#endfor
```
I am reciveing errors like these:

`AttributeError: <Group 0x15226d4bcc8> does not have member 'file`

The commands `group2dict` and `group_items` work in getting a list or dictionary of the files for me (seemingly the former works better?) and printing their names but the issue comes with actually reading the data files.

Any help would be greatly appreciated!

**Comment by newville** [comment]
@killiantallman For looping through the groups saved in an Athena Project do this:

    project = read_athena('MyProject.prj')
    for name, group in project._athena_groups.items():
         print("Processing group named  ", name )
        show(group)
   #endfor    

That is `project._athena_group` has the dictionary of name:group pairs.

Does that make sense?

**Comment by killiantallman** [comment]
@newville It doesn't make a ton of sense to me. When trying to run your code I am getting the following error which doesn't recognize the variable group:
```
Traceback (most recent calls last): 
for name, group in project._athena_groups.items():
    print("Processing group named  ", name )
    show(group)
#endfor
   File FitDataLoop.lar, line 13
SyntaxError: invalid symbol name 'group'
```

When I take out the group variable it prints out the files that exist as groups successfully. However, it doesn't seem to be able to grab any information from the file group. An example would be that I cannot print out e0 values for each group (using this a test to see if I can access the group attributes in a loop) by sticking in the loop:

`print(file.e0)`

**Comment by newville** [comment]
@killiantallman Sorry, my bad.  'groups'  is a builtin name.  But try this:

    project = read_athena('MyProject.prj')
    print(dir(project))
    print(project._athena_groups)
    for name, g in project._athena_groups.items():
         print("Processing group named  ", name )
        show(g)
    #endfor

**Comment by killiantallman** [comment]
@newville Yes that works and now makes complete sense. Thank you!

**Comment by maurov** [comment]
This issue is solved, so I close it.
