### ISSUE TITLE
Convert Athena project files to HDF5

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#265]
@newville I am planning to implement a simple function in `larch.io` to convert an Athena project file to HDF5. This may turn useful for reading data back in other applications and let `xas_viewer` to export to HDF5.

The structure I have in mind is very simple, without any Nexus directive:

```
(/ = HDF5 group)
(: = HDF5 dataset)
/
| - _athena_header: 
| - _athena_journal:
( for group in _athena_groups:
 | - group_name/
 | -- attributes:  # provenance, athena_id, label, ...
 | -- subgroups/   # athena_params, bkg_params ...
 | ---- parameters:  # xmax, xmin, annotation, ...
 | -- arrays:  # energy, mu, 
)
```

Another mapping could be similar to [HDF5 mapping of a Specfile in SILX](http://www.silx.org/doc/silx/latest/modules/io/spech5.html), where parameters would go in `instrument/positioners` group and the arrays would go in the `measurement` group.

If you have a preference or any thoughts what would be the best mapping of an Athena project to HDF5, please, comment here, otherwise I will fire a merge request at a certain point.

*Note*: this differs from #11, even if at a certain point it would be nice to save/restore data to/from HDF5 only.

**Comment by newville** [comment]
@maurov Yes, I think that Athena2HDF5 would be interesting, including having XAS Viewer support both and do a conversion between them.

I don't have a strong affinity for the Athena Project format itself, except it works (!! @bruceravel ).   Of course, it holds arrays of data following a clear naming convention which would be easy to map from Zip to HDF5.  But an Athena Group also holds quite a bit of configuration/settings data, essentially mapped as a dictionary.   Sadly, HDF5 does not directly support a dict/hash type (among its flaws -- hey, I use it everyday).  I sort of assume that SILX must have a common solution to this, perhaps as simple as a mapping of a dict to a JSON string.

If so, that seems like Athena->HDF5 and HDF5->Athena translations would be reasonably straightforward.   I'd say go for it!

Stay Safe!

**Comment by maurov** [comment]
OK, I did a [quick and dirty Athena -> HDF5 function](https://github.com/maurov/xraylarch/blob/727d4892ce12564bc5bdfbe440af1bcab16133e2/larch/io/athena_to_hdf5.py#L16) that does what I currently need for easily viewing Athena files with `silx view`.

It may be implemented in a more elegant way, but if there are no objections, I would propose to merge this for the moment.

**Comment by newville** [comment]
@maurov Does that mean that each processing parameter (e0, etc -- all scalars) each gets its own dataset?  Is that how silx maps dictionaries to hdf5?  That might be ok...

**Comment by maurov** [comment]
@newville here a [more elegant solution using AthenaProject.as_dict() + silx.io.dictdump.dicttoh5](https://github.com/maurov/xraylarch/blob/1808ded6d964ce27d9803250ca407bf502850972/larch/io/athena_to_hdf5.py#L18). Please, have a look. Comments are welcome.

I have noticed that the `athena_params.__dict__` group is not mapped as the others `*_params` groups, so this gives a weird conversion to HDF5. I do not understand why from the code of `AthenaProject().read()`.

**Comment by maurov** [comment]
Here a `silx view` screenshot of `cyanobacteria.prj` currently mapped in HDF5

![image](https://user-images.githubusercontent.com/545294/77046866-0533aa80-69c4-11ea-8cf9-1f5903ac3f2a.png)

I have decided to put all groups in `groups` and parameters in `_params`.

**Comment by newville** [comment]
@maurov That use of silx's `dict2h5()` does look simpler.   So, yes!

One suggestion:  I would make the `match = kws.get("match", None)` etc into keyword arguments of the function, with default values.  That way, the signature is a better part of the documentation.

I think we should be able to completely remove all of the ugly `_larch=_larch` and `_larch=None` here (needs changes to `larch.io.AthenaProject`, but I think it is doable).  At this point, I believe the `_larch` instance is just getting passed around to set the "default XAFS group", which is probably a bad idea anyway.  At this point, I think we definitely want to encourage "Python library", to "python-like interactive session".     That is, I think the call to read the Athena Project file should just be (after fixes):

```
    aprj = AthenaProject(filename, match=match, do_preedge=do_preedge, 
                         do_bkg=do_bkg, do_fft=do_fft use_hashkey=use_hashkey)
    adict = aprj.as_dict()
```

I'll try to make that change soon.   On the slightly off-topic but ever-present situation, I'm going to try to spend time at the lab today (we were scheduled to be commissioning vertical-deflecting HERFD at V K-edge this week!) as it looks like we are ordered to "shelter in place" for two weeks starting tomorrow.  So there will be plenty of time for code, documentation, reviewing papers, web work (and baking bread, playing guitar, and netflix binging).   Hope you're doing well!

**Comment by maurov** [comment]
> One suggestion: I would make the `match = kws.get("match", None)` etc into keyword arguments of the function, with default values. That way, the signature is a better part of the documentation.

OK, done.
