### ISSUE TITLE
plot_chifit() rmax shows no effect

### ISSUE THREAD

**Issue by Nothinel** [xraypy/xraylarch#268]
I have noticed, that using the rmax option in the plot_chifit() function does not do anything. I can set it to any datatype or value, without any effect. I am currently using Version 0.9.47 of larch. The prior fit and the plots are produced and everything except for this option works.

**Comment by newville** [comment]
@Nothinel OK, thanks for the report -- I'll check that out.

**Comment by newville** [comment]
@Nothinel I think this is addressed in the master branch.

**Comment by Nothinel** [comment]
The fix works great! Thank you.
