### ISSUE TITLE
problems creating Parameter groups for fitting

### ISSUE THREAD

**Issue by erdzeichen** [xraypy/xraylarch#269]
Hej,
I'm trying to get a minimum fitting to work in python and stumble over the group creation over nd over. After testing a few things i believe this must b a bug

amp=larch.fitting.param(value=0.9,vary=True, min=0.6, max=1.1)
param=larch.fitting.ParameterGroup(amp=amp)
param=larch.fitting.parameter_group(amp=amp)

(for both)
AttributeError: 'NoneType' object has no attribute 'add'

**Comment by newville** [comment]
@erdzeichen Hm, yes I can reproduce that.  I think that usage should be avoided...

Can you give a little more context for what you are trying to do?

For sure the idea of fitting with "Parameter" Group is sort from the point-of-view of working "in Larch", as opposed to Python directly.  It also turns out to be some of the oldest Larch code and mostly pre-dating a mature and separate `lmfit`.  

For using `feffit()`, I would recommend just making a simple Group for the parameters. 




If you are doing peak-fitting, I would definitely recommend just using lmfit from Python.

**Comment by erdzeichen** [comment]
Hi Matt, if I use a Group I get the same error. In principle I try to use ifeffit in python so I don't have to rewrite the path fitting. Any working approach would be great. The approach in the  manual only works inside larch. 
Thanks Jens

**Comment by newville** [comment]
@erdzeichen A "working approach" to what?  You have not said what you are trying to do.  
For sure, you could make a Larch session from Python and use that.

**Comment by newville** [comment]
@erdzeichen If you are trying to do "feffit()" in Python with Larch, the example below should show you how to create the (`lmfit`-based) Parameters and how to pass around a `_larch` interpreter instance.  That is, although many of the Larch functions no long need the irritating `_larch=_larch` argument, the `feffit_xxx` functions do still need to get a reference to some of the global state.  This could probably be cleaned up (or more hidden).

But I suspect the problem you were having may be that the "Larch way" for creating a Parameter is more tolerant than the `lmfit` way.   So note the `Parameter()` syntax when creating the Group of Parameters.... This should definitely be cleaned up!

```python

from larch import Group, Interpreter
from larch.io import read_ascii
from larch.xafs import autobk, feffpath
from larch.xafs import feffit_transform, feffit_dataset, feffit, feffit_report
from larch.fitting import Parameter, Parameters
from larch.wxlib.xafsplots import plot_chifit

cu_data = read_ascii('examples/xafsdata/cu_metal_rt.xdi')
autobk(cu_data.energy, cu_data.mutrans, group=cu_data, rbkg=1.0, kw=2)

_larch = Interpreter()

## Note: Parameter() requires a name, but the Group name is actually what is used by feffit! 
## this should be cleaned up!
pars = Group(amp   = Parameter('amp', value=1.0, min=0),
             del_e0= Parameter('del_e0', value=0.0),
             sig2  = Parameter('sig2', value=0.002, min=0),
             del_r = Parameter('del_r', value=0.0))

path1 = feffpath('examples/feffit/feffcu01.dat',
                 s02='amp', e0='del_e0',
                 sigma2='sig2', deltar='del_r', _larch=_larch)

# set tranform / fit ranges
trans = feffit_transform(kmin=3, kmax=17, kw=2, dk=4,
                         window='kaiser', rmin=1.4, rmax=3.0, _larch=_larch)


dset = feffit_dataset(data=cu_data, pathlist=[path1], transform=trans, _larch=_larch)

out = feffit(pars, dset, _larch=_larch)
print(feffit_report(out))
```

Anyway, I hope that helps get you going but if not, please describe what you are trying to do.

**Comment by erdzeichen** [comment]
Thank you, this worked.
Best
 Jens

**Comment by newville** [comment]
@erdzeichen OK, thanks and glad you have something that is working.  Still,  it does seem like this should be done better, like just using as-plain-as-possible `lmfit` Parameters....
