### ISSUE TITLE
[xas_viewer] error in creating new group from `read_specfile`

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#278]
This issue is related to #277. @newville I'd like some help/advice.

When I read [ABCF002.DAT](https://github.com/xraypy/xraylarch/files/5696952/ABCF002.zip) (unzip it) in xas_viewer, I can correctly see the preview:

![image](https://user-images.githubusercontent.com/545294/102237595-1aa71800-3ef5-11eb-8875-7b937a6521c9.png)

But when I click "OK" button I get the following error:

```
Traceback (most recent call last):
  File "/users/blissadm/local/xraylarch/larch/wxlib/columnframe.py", line 693, in onOK
    array_sel=self.array_sel)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasgui.py", line 989, in onRead_OK
    self.install_group(groupname, filename, overwrite=overwrite)
  File "/users/blissadm/local/xraylarch/larch/wxxas/xasgui.py", line 1032, in install_group
    thisgroup = getattr(self.larch.symtable, groupname)
AttributeError: 'SymbolTable' object has no attribute 'abcf00001'
```

My reading function is `read_specfile`, but I am lost in the GUI part.

Thanks for the help!
Mauro

**Comment by newville** [comment]
@maurov Hm, not entirely sure -- I'll take a look.
