### ISSUE TITLE
how to process data in original xafs .txt file?  

### ISSUE THREAD

**Issue by minghuisvn** [xraypy/xraylarch#279]
I have many xafs datas in the original form, .txt file. I want to program to process these data by utilizing the larch python package automatically, but i only know how to  process .prj file  which is commonly obtained by athena program. How can i process the .txt file directly using the large package? Are there any detailed instructions or examples showing how  to use larch python package? Thank you!

**Comment by newville** [comment]
@minghuisvn Well, what is "the original form"?   Larch and its XAS_Viewer app can read data from many plain text files.  It is always a challenge to support all variations of data files.    But, if you have many files in the same format (and it is not *too* crazy ;)) it is probably not very hard to make that readable into Larch.

I would suggest trying to read these files into XAS Viewer and/or trying the "read_ascii()" function of Larch.  If that doesn't make it easy enough to get your data in, I suggest posting an example file or two.

**Comment by minghuisvn** [comment]
@newville Thanks for your replying.I am familiar with python, so i want to write a script using larch as the python package to batch-process  data, ca. 200 spectra for the compound treated under different conditions. My object is to complete background substraction, normalization and to obtain the metal atom valence information in the substance. Looking up for the examples in the examples folder of larch github project, i found two related examples written in jupyter notebook(directory is " xraylarch/examples/Jupyter"). However, these two examples started working from .prj file produced by athena programe, not treating .txt file directly. 
My data files are same .txt format as follows:
8 7506.808 0.0766036
24 7507.064 0.0788118
40 7507.320 0.0778053
56 7507.576 0.0771937
72 7507.833 0.0764318
88 7508.089 0.0763349
104 7508.345 0.0782731
120 7508.601 0.0762191
136 7508.857 0.0786603
152 7509.114 0.0742137
168 7509.370 0.0802842
184 7509.626 0.0748937
200 7509.882 0.0815849
216 7510.139 0.0745616
232 7510.395 0.0800267
248 7510.651 0.0751146
264 7510.908 0.0792760
280 7511.164 0.0792167
. It is my first time to process xafs data. Are there some practical, best  python-related, guidlines to refer to. Thank you!

**Comment by newville** [comment]
@minghuisvn have you tried using "read_ascii()"? I think that should work... See https://xraypy.github.io/xraylarch/data/index.html#io.read_ascii

If you need help, post code (minimal but complete) that shows what you are trying to do.

**Comment by maurov** [comment]
@minghuisvn I assume this is solved by `read_ascii`. If not, react here by posting a complete minimal example of code and an example of dataset.
