### ISSUE TITLE
Typo in learn_regress.py

### ISSUE THREAD

**Issue by joelager** [xraypy/xraylarch#284]
In function lasso_predict.py:

line 241
            model.model.__repr__().startswith('PLS'))

'PLS' should be 'Lasso'

Noticed this in running one of the tutorial/demo files in the context of using larch in my "Advanced Spectroscopy" graduate class

**Comment by newville** [comment]
@joelager Oh, thanks - will fix!

**Comment by newville** [comment]
@joelager fixed
