### ISSUE TITLE
[xas_viewer] application freezing when importing the same scan twice from a specfile

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#287]
@newville I have observed that `xas_viewer` get stuck if you import the same scan twice from a specfile. Here how to reproduce it:

- import [ABCF002.DAT](https://github.com/xraypy/xraylarch/files/5696952/ABCF002.zip) with counter `absT2`.
- import [ABCF002.DAT](https://github.com/xraypy/xraylarch/files/5696952/ABCF002.zip) with counter `absT1`.

Ideas how to fix it are welcome.

Thanks!

**Comment by newville** [comment]
@maurov  Oh, I can reproduce that.  Or, for me, it took a very, very long time.  I think it must be a mistake in the 'pick a groupname and makes sure it does not exist' loop -- probably didn't test that but it should be easy to fix.

**Comment by maurov** [comment]
Yes, the default imported group name should also contain the name of the imported counter, e.g. `ABCF000.DAT_scan12.1_absT1`

**Comment by newville** [comment]
@maurov I think this is now fixed in the master branch.

**Comment by maurov** [comment]
Fixed at https://github.com/xraypy/xraylarch/commit/ac82956ebf9beb68b84294d0e67f8001887e2f62
