### ISSUE TITLE
[xas_viewer][specfile] keV to eV conversion dialog at import level

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#288]
After importing a scan from a Spec file and converting units from keV to eV the same energy conversion dialog reappears when interacting with the GUI, for example by plotting the MBACK background or when picking the pre-edge range.

@newville probably the best here is to pop the energy conversion dialog at the import level and apply to all imported groups (if multiple scans).

**Comment by newville** [comment]
Yeah, I think it should probably have a dropdown (with a guess) of energy units for the energy array and do the conversion before the data gets "installed".  That would prevent the repeated pop-up dialogs.  The regular "read ascii file" dialog should probably do that too for people reading data from beamlines that save data in keV (or degrees).  On the ToDo list!

**Comment by newville** [comment]
@maurov OK, the master branch now has a couple of changes for reading specfiles with xas_viewer:

* the conversion of energy units (to eV from keV or from degrees, with mono d-spacing) now happens in the Importer window (both Specfile Importer and ColumnFile Importer).  
* the same routine for "guess energy units" used in the main xas_viewer is used for these as well.  If the datatype is "xas", the displayed plot in the Importer will show the data converted to eV.
* the settings (with arrays to use, mono d-spacing) are remembered during a xas_viewer session and used as default values when opening another file (or the same file again).
* read_specfile() tries to extract the file and scan heder (from 'instrument/specfile/scan_header' and 'instrument/specfile/file_header'  -- should those be abstracted out as the other urls are?) and Specfile Importer will show those.

I think these are all improvements, but only lightly tested.  Let me know how this works for you and if you have any thoughts on what is missing, wrong, etc.

**Comment by maurov** [comment]
@newville you did a wonderful work implementing all this, thanks! I have deployed on the beamline the `master` version and at a first test everything seems to work fine.
Regarding your last point, I will work soon in the URLs specification for reading BLISS-type HDF5 files too, as the mapping is not the same. I will update the list of tasks and close this issue for clarity.
