### ISSUE TITLE
XAS Viewer / Area under gaussian peak / Amplitude

### ISSUE THREAD

**Issue by Teerarat6072064723** [xraypy/xraylarch#291]
Hi everyone

I would like to know how can I get the integrated area under gaussian peak (is that amplitude in XAS Viewer?) since I can found it after using peak fit in origin program. (Im doing pre-edge peak fit of Fe K-edge)

Thank you in advance.

**Comment by newville** [comment]
@Teerarat6072064723 Yes, Amplitude is the strength of a unit-normalized Gaussian, and so will be the area under the curve of the idealized Gaussian function. The Height is also reported, which will be the maximum intensity - at the centroid - of that Gaussian.    Those meanings of Amplitude and Height will also be used for Lorentzian, Voigt, and other peak-like functions (though for some of the more exotic functions, these may only be approximate).
