### ISSUE TITLE
[wx/cif_browser] add possibility to load a cif file from disk

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#301]
@newville the "cif browser" is great, thanks! For this first realease, I would only add a button in the GUI to give the user the possibility to load  CIF file from disk.

**Comment by newville** [comment]
@maurov You can open a CIF file and use that (File->Open CIF FIle).  That will actually insert the CIF data into the users sqlite database, so they don't have to keep it around.

Now, how well this works is an open question.  CIFs are notoriously complex and bad at uniformity.  I tested with 3(!) files from the crystallography.net site and had to make some changes for how CIFs are parsed based on those.  So, I'm sure it will be possible to break, but I think it is at the point of either running a huge test suite or waiting for bug reports.

FWIW, not all CIFs that can be read (including some in the AmMin database) can actually generate a valid Feff file, but it seems that most of them can....

**Comment by maurov** [comment]
OK, great! I close this issue now. Yes, testing various sources of CIF files is definitively required. Hoping this will come with user usage!
