### ISSUE TITLE
[wxlib/specfile_importer] error importing files from ESRF-BM30

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#303]
@newville  I cannot successfully import [testlarch_bm30_08Jun21.zip](https://github.com/xraypy/xraylarch/files/6701753/testlarch_bm30_08Jun21.zip) (unzip it before use) from the specfile_importer GUI.

Scan 7 (counter absF1) is correctly read/plotted in the *Build Arrays* panel, but at the importing level I get the *Select Energy Units to convert to eV* panel that prevents making the group usable.

![testlarch_bm30_08Jun21_screenshot](https://user-images.githubusercontent.com/545294/123096944-ea09e300-d42f-11eb-8e90-3fd18e901b8e.png)

I do not see any issue from the "command line" part, so I do not really know how to debug this. If you could have a look, it would be great!

Solving this is somewhat "mandatory" for having `0.9.53` a good release for our users.

PS: silx 0.15.2 is required to read such file.

**Comment by newville** [comment]
@maurov Thanks-- I check it out.

**Comment by newville** [comment]
@maurov silx 0.15.2 spews a lot of warnings for this file.  Is that normal?  

Anyway, the reading problem was that I was assuming that the displayed "extended scan label" could be split on ':'.   to generate the command `specfile.get_scan(scan='7.1')`.  Changing that to "split on '|'" allows the scans to be read in.  

Fixed in master (but master is not extremely stable this week!)

**Comment by maurov** [comment]
@newville thank you for looking into this!

> @maurov silx 0.15.2 spews a lot of warnings for this file. Is that normal?

Yes, the warnings come because this file has a wrong number of positioners with respect to the list of available motors. If you find this annoying, you could lower the logging level for `silx`:

```python
import logging
sx_logger = logging.getLogger("silx")
sx_logger.setLevel(logging.ERROR)
```

> Anyway, the reading problem was that I was assuming that the displayed "extended scan label" could be split on ':'. to generate the command `specfile.get_scan(scan='7.1')`. Changing that to "split on '|'" allows the scans to be read in.

Ah, great for catching this. In fact, I had to put `|` instead of `:` when building the "extended scan label". This is required because sometime the BLISS files may have a scan "number" that contains the `:` character, like `specfile.get_scan(scan='something: 1.1')`

> Fixed in master (but master is not extremely stable this week!)

OK, seems to work fine, closing this issue.

**Comment by newville** [comment]
@maurov Great -- the '|' vs ':' all makes sense.  
I don't really have a preference on setting the silx logging level -- what do you think is most appropriate?

**Comment by maurov** [comment]
> I don't really have a preference on setting the silx logging level -- what do you think is most appropriate?

I propose to leave like this for now, that is, not manually setting the logging level for silx (warning by default).
