### ISSUE TITLE
Problems to import Larch build-in functions to python 

### ISSUE THREAD

**Issue by duoduoss** [xraypy/xraylarch#304]
Hello, 

I am learning to use Larch in python for EXAFS fitting, but I had problems to import some build-in functions such as show() and which(). I assume I didn't even find the right path for those functions. I posted what I got below. 

I would appreciate very much if you could take a look and give some instructions on how to fix them.

Thanks in advance, 
Best regards,

=====================
For example, after reading a data file (feo), I tried the following: 
-- from larch.utils.show import show
-- show
-- <function larch.utils.show.show(sym=None, with_private=False, with_color=True, color=None, color2=None, truncate=True, with_methods=True, _larch=None)>
-- show(feo)
Traceback (most recent call last):
  File "<ipython-input-29-fcd9259e055f>", line 1, in <module>
    show(feo)
  File "C:\ProgramData\xrayLarch\lib\site-packages\larch\utils\show.py", line 76, in show
    symtable = _larch.symtable
AttributeError: 'NoneType' object has no attribute 'symtable'. 

And for which(), I coudn't find where to import it. 
-- help(which) 
Traceback (most recent call last):
  File "<ipython-input-33-61e0fcca55ab>", line 1, in <module>
    help(which)
NameError: name 'which' is not defined

**Comment by newville** [comment]
@duoduoss yeah, some of the functionality in "Larch shell language" don't translate super easily to plain Python.   For example, that "show()" command is basically a fancy "dir()", maybe

    for key in dir(group):  print(key, getattr(group, key))

"Which" is harder to emulate but needed less (or "different"), because you have to import things in order to find them.

**Comment by duoduoss** [comment]
@newville Thank you very much! It works when I replace the 'show(path1)' with the syntax you provided. The output looks different from the example in "13.7.7. Example: Reading a Feff file", but contains most of the information:

_calc_chi <bound method FeffPathGroup._calc_chi of <FeffPath Group feff0001.dat>>
_feffdat <Feff.dat File Group: feff0001.dat>
chi None
create_path_params <bound method FeffPathGroup.create_path_params of <FeffPath Group feff0001.dat>>
create_spline_coefs <bound method FeffPathGroup.create_spline_coefs of <FeffPath Group feff0001.dat>>
degen 12.0
deltar 0.0
e0 0.0
ei 0.0
filename feff0001.dat
fourth 0.0
geom [('Cu', 29, 0, 63.546, 0.0, 0.0, 0.0), ('Cu', 29, 1, 63.546, 0.0, -1.8016, 1.8016)]
k None
label pfh2ced6i
nleg 2
params None
path_paramvals <bound method FeffPathGroup.path_paramvals of <FeffPath Group feff0001.dat>>
reff 2.5478
report <bound method FeffPathGroup.report of <FeffPath Group feff0001.dat>>
rmass 31.773000000000003
s02 1.0
sigma2 0.0
spline_coefs {'pha': <scipy.interpolate.fitpack2.InterpolatedUnivariateSpline object at 0x000001EB1C7FB580>, 'amp': <scipy.interpolate.fitpack2.InterpolatedUnivariateSpline object at 0x000001EB1C7FB6A0>, 'rep': <scipy.interpolate.fitpack2.InterpolatedUnivariateSpline object at 0x000001EB1C7FBE80>, 'lam': <scipy.interpolate.fitpack2.InterpolatedUnivariateSpline object at 0x000001EB1C7FBD00>}
store_feffdat <bound method FeffPathGroup.store_feffdat of <FeffPath Group feff0001.dat>>
third 0.0

**Comment by maurov** [comment]
@duoduoss, in my opinion, if you want to use Larch as a Python library, you should not import commands that are part of Larch's domain-specific language (DSL). The DSL commands are meant to be used in [Larch scripts](https://xraypy.github.io/xraylarch/larchlang.html) only. Please, could you tell us if our replies are clear and we can close this issue?

**Comment by duoduoss** [comment]
Yes, they are very clear! Thank you very much!
