### ISSUE TITLE
[xas_viewer] current group plot should remember the type of plot?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#305]
@newville currently in xas_viewer, when clicking on a given group the plot reverts to default "Normalized mu(E)". I think it is more convenient to keep the plot type to the last one selected when switching from one group to another. What do you think?

Furthermore, it seems to me that the "Plot current group" button is redundant as this action is performed when clicking on the groups panel or when changing the plot type in the combo box.

**Comment by newville** [comment]
@maurov good point -  using the last selection would be better. I'll look into it.
