### ISSUE TITLE
[xas_viewer/AthenaProject] Wrong group names when reading back from a manually created Athena project

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#307]
@newville I do not understand why group names are not correctly read from an AthenaProject manually created. Here a complete minimal example:

```python
import numpy as np
import tempfile
from larch import Group
from larch.io import AthenaProject

def dummy_mu(ene, step=1, e0=7112, width=1):
    bkg = step*(np.arctan((ene-e0)/width)/np.pi+0.5)
    slp = -ene*step/1000
    noise = np.random.normal(0, step/100, ene.shape)
    return bkg+slp+noise

tf = tempfile.mktemp(prefix='athenatestout_', suffix=".prj")
print(tf)
apj = AthenaProject(tf)
ene = np.linspace(7000, 7500, 500)
for cnt in ['ch1', 'ch2', 'ch3']:
    mu = dummy_mu(ene)
    g = Group(name=cnt, athena_id=cnt, energy=ene, mu=mu)
    apj.add_group(g)
apj.save()
```

This is what I get when reading back the Athena project file with xas_viewer:

![image](https://user-images.githubusercontent.com/545294/125801239-5322c97f-647a-45df-9023-64dfca22e01b.png)

I was expecting to have the group names as `ch1` , `ch2`, `ch3`. Is that a bug or I am simply missing how to correctly create groups in an Athena project file?

**Comment by newville** [comment]
@maurov Yeah, I think that should be 'ch1', 'ch2', etc.  I'll look.  Hoping to get out 0.9.54 with lots of small changes fairly soon.

**Comment by newville** [comment]
@maurov this is now fixed in the master branch, hoping to push out recent bugfixes 0.9.54 in a few days.

**Comment by maurov** [comment]
@newville thanks for fixing this.

**Comment by maurov** [comment]
@newville I think there is still an attribute I am missing in the group creation. When trying to plot in the EXAFS panel, I get the following error:

```
Traceback (most recent call last):
  File "/users/blissadm/local/xraylarch/larch/wxxas/exafs_panel.py", line 595, in onPlotSel
    self.process(dgroup=dgroup, read_form=False)
  File "/users/blissadm/local/xraylarch/larch/wxxas/exafs_panel.py", line 527, in process
    self.larch_eval(autobk_cmd.format(**conf))
KeyError: 'group'
```
If I manually rename the groups in the GUI, then the EXAFS plot works. Is there an unique group attribute that is used to identify a group? Is it `groupname`, `athena_id` or something else?

**Comment by newville** [comment]
@maurov hm, I'm not seeing such an error with the project file built with your script.  But I can see that it might be possible for 'group' to not be set.  So, I'll try to fix that...

**Comment by maurov** [comment]
Sorry, I forgot to say that I get this error when I try to plot all selected groups as chi(k).

**Comment by newville** [comment]
@maurov yeah, I sort of guessed that, but I don't see that.  Anyway, I think I pushed code that will avoid this, if not fix it.

**Comment by maurov** [comment]
OK, great! it seems to work now. Thank you very much indeed for your prompt help!
