### ISSUE TITLE
feature request - deglitch data dialog, show data as X(k) and not just mu(E)

### ISSUE THREAD

**Issue by emilioheredia-source** [xraypy/xraylarch#312]
Hi Matt, thanks for larch. I've been using it and it's incredible (and best of all, improving by the day).
I just have a small request that will make deglitching data easier for me, and I hope many others.
I've data that looks like this 
![image](https://user-images.githubusercontent.com/60711791/129604625-f66385c7-b883-41e5-a431-94bdd707a858.png)

I can see the points with problems in x(k), for instance, close to 3.24 inv Ang, but when plotted as mu(E) I cannot even find the glitch location. One alternative will be to calculate the energy that corresponds to that value of k but it's a little complicated and worst still, the glitch might not be visible when plotting without k-weighting.
The feature I wanted to suggest is to make x(k) one of the plot types (options) that can be used with the deglitch data dialog, so glitches like the ones in the picture can be easily removed (ideally, with the remove point tool).
If not possible, could at least the status bar at the bottom of a x(k) plot show the energies that correspond to the values of k? In this way, I can easily find the corresponding point in a mu(E) plot (that's what I used to do with Athena).
Thanks again for larch, for all your training videos, and for considering this.
Emilio.

**Comment by newville** [comment]
@emilioheredia-source. Good suggestion - on the Todo list!

**Comment by newville** [comment]
this is now much better in 0.9.60
