### ISSUE TITLE
Add Jupyter notebooks examples

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#324]
@charlesll are you still willing to provide examples of Jupyter Notebooks?

> On another note: are you interested in Jupyter Notebook examples of the use of Larch? 
> If yes, I could push some to the examples folder at the occasion.

Yes, that would be very nice.   Having a Larch kernel for Jupyter would also be kinda cool for many uses.  It looks like it is probably not too hard, but I have not gone very far into that idea.

_Originally posted by @newville in https://github.com/xraypy/xraylarch/issues/249#issuecomment-419496245_

**Comment by newville** [comment]
@maurov  +1 on this from me. Not using Jupyter much myself, I feel like this would be a great contribution from someone who does use Jupyter regularly so that they could actually add nicely formatted annotations, plots, etc.

**Comment by charlesll** [comment]
@maurov Yes we actually with Larch in Jupyter, it's quite easy and for the folks that like Jupyter, it's very pleasant!

I will see what I can provide! I have some Fe K-edge XANES or Ti K-edge spectra that could be used as examples.
