### ISSUE TITLE
[xas_viewer] save project behaviour as Athena (or common GUIs)

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#325]
@newville various users have reported the following wishes (as it is in Athena):

- [x] "File -> Save project" should act as "save the current project by silently overwriting it". Associated to the "CTRL-S" keyboard shortcut.
- [x] Add "File -> Save project as..." action.

They make sense to me. Any argument against implementing them?

**Comment by newville** [comment]
@maurov Yes, I agree. I will plan to do that this weekend.

**Comment by maurov** [comment]
Done in https://github.com/xraypy/xraylarch/commit/4624aa4f1ff96139959aa0e1f363cad72dab1ec9
