### ISSUE TITLE
Store group journal

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#326]
Each group object should keep a history for the following actions:

- merge
- deglitch
- energy calibration

It should be saved to the Athena project file and have the possibility to show it in `xas_viewer` in a dialog accessible by right click on the group label.

**Comment by newville** [comment]
@maurov  I like this idea. For merging and energy calibration, I think that "what to do/store" is clear.  For merging, it is a little less clear.  It should probably be the names of the files, and maybe the list of histories for them (in case you are merging deglitched spectra, for example....).    

I guess the history should also describe how the file was read (which columns were used, etc). Might need some more thought or discussion on how far back you need to go, and how to describe that history....  Maybe it needs to be the text of the larch code needed to reproduce the result?

**Comment by maurov** [comment]
After discussion with @newville, this could be implemented as:

- [ ] add a `journal` attribute to Larch `Group`, which is a string or a list of strings (to see at the usage what is the best solution)
- [ ] store/restore this information from Athena project files
- [ ] exporting to CSV adds the whole journal as commented header (starting with `#`
- [ ] when reading data into a Group, the `header` will go into the journal.
- [ ] when merging groups, the name/filename of the merged groups go into the journal
- [ ] the journal should be visible from `xas_viewer` (e.g. right click on the group name to show a new window with the journal
- [ ] the user may add further comments to the journal via this window

**Comment by newville** [comment]
@maurov I've made some progress on this, and on "Saved Session/Project File".  I thought I'd give a progress report:

For "Group Journal", Not all of the requested features are in place yet, but the XAFS processing steps and the data-manipulation from the Data Dialogs do go into a Journal.  There is a Journal class that stores a list of "Entries", with keyword, value, and datetime.   The XAFS processing functions use a "Make_CallArgs" decorator that has been making a "<fcn_name>_call_args" dict that might get put in a group's "details" section.  This now also writes that to the Journal, recording when each function was called.   In addition, the GUI code might also write to the Journal, as some steps (say, Peak Fitting, PCA fitting, etc) do not use this decorator (and may not exactly work on XAFS data groups). 

So, I think this goes a long way for the Journal idea.  

-    A group's journal is saved/restored from Larch Project Files.  
-    A journal can be saved to CSV (well, tab-separated)
-    journal values are most dicts:  could be converted from {'e0': 7120.2, 'pre1': -200, ...}  to 'e0=7120.0, pre1=-200'?
-    file header is not in the Journal: could be, but not certain?
-    merging lists what groups were merged, but does not merge journals
-    data processing steps (e0 shifts, deglitching) are recorded
-    the journal can be viewed from the File Menu:  could add right-click? 
-    right now the user cannot add a note to the Journal, but that's a good idea.

If you have any preferences for the things with question marks or other suggestions, let me know. 

One thing that occurred to me was that a Larch Project/Session could include a "Documents" or "Attachments" list for say binary blobs of images, PDFs, etc, to attach to the Project (and saved/restored in the Project file).  Some of these (PNGs/PDFs) could be displayed from the GUI, or re-exported to the user's computer.

For the Project File (I know, also at #363), basic save/read is working, as is "autosaving Larch Session" every 15 minutes (will be an editable setting (#356) to the user's `.larch` folder.   Some of the "Processing Tabs" (Feffit, PCA, PeakFit, etc) are not yet recognizing that they need to read and "install" data from that restored session (but that will happen soon).

**Comment by maurov** [comment]
@newville thank you very much indeed for your progress report. What you have done so far is great! Thanks. Below some comments from my side.

>     * file header is not in the Journal: could be, but not certain?

Yes,  I think it is important to include the file header into the group journal when reading data. Furthermore, the journal should keep track of the columns names used to create the group itself.

>     * the journal can be viewed from the File Menu:  could add right-click?

Yes, I think right-click is more intuitive than "show journal for this group" into the menu (personal preference but also from users feedback). By the way, I suggest that the "per group" actions of the "Groups" menu (like "Copy this group", "Rename this group") should go to right-click.
 
>     * right now the user cannot add a note to the Journal, but that's a good idea.

Yes, this would be very nice to have too. Each note should be associated to a time entry.
 
> One thing that occurred to me was that a Larch Project/Session could include a "Documents" or "Attachments" list for say binary blobs of images, PDFs, etc, to attach to the Project (and saved/restored in the Project file). Some of these (PNGs/PDFs) could be displayed from the GUI, or re-exported to the user's computer.

Yes, this would be great to have too.

**Comment by newville** [comment]
I think we have a good start on Journal, even if we might want to do more
