### ISSUE TITLE
Deglitch data in Chi(k)

### ISSUE THREAD

**Issue by Ardalanhayatifar** [xraypy/xraylarch#334]
Similar to ```Indicators``` feature in Athena, is it possible to view points both in energy (eV) and wavenumber A<sup>-1</sup> and then remove the glitches using the ```Deglitch Data``` menu which reads in energy (eV)?

**Comment by newville** [comment]
@Ardalanhayatifar sorry for the delay. I guess it would be possible to display the wavenumber along with the energy, maybe on the top axes?  I'll have to think about that...

**Comment by Ardalanhayatifar** [comment]
Hi Matt. You’re totally fine. I hope you’ve had a great break.
I tried to use ```configure plot``` but couldn’t add another x-axis. The glitch is only visible in Chi(k):

<img width="960" alt="glitch" src="https://user-images.githubusercontent.com/28695266/148255553-7c98fbaa-3d0a-415c-9830-4a2e2ece1603.png">

When clicked on the point it selects it in A^(-1) and this would not work in ```Deglitch Data```:

<img width="1102" alt="deglitch_2" src="https://user-images.githubusercontent.com/28695266/148255920-763ea889-e37c-4dde-85c1-6c9e5b547951.png">

The thing that would be helpful is to find the exact eV for this point. Trying to convert the value from A^(-1) to eV was not pixel-perfect. 
Also I’m sorry, my friend saw a similar issue (https://github.com/xraypy/xraylarch/issues/312#issue-971950111) after we posted this question.

**Comment by newville** [comment]
I think this is much better with 0.9.60
