### ISSUE TITLE
Issue can't open Larch applications after install with --devel option

### ISSUE THREAD

**Issue by LaurenPincus** [xraypy/xraylarch#335]
Hi @maurov thanks for your quick reply on the mailing list. I was able to reinstall Larch using the --devel option. However I am still having an issue where I am unable to open any of the applications. The icon appears in my dock for a second and then the application closes itself. The only application which opens is Larch CLI which gives the following error in the script: 

/Users/laurenpincus/xraylarch/python.app/Contents/MacOS/python /Users/laurenpincus/xraylarch/bin/larch 
(base) laurenpincus@lnp24mbp2020 ~ % /Users/laurenpincus/xraylarch/python.app/Contents/MacOS/python /Users/laurenpincus/xraylarch/bin/larch 
Traceback (most recent call last):
  File "/Users/laurenpincus/xraylarch/bin/larch", line 8, in <module>
    sys.exit(run_larch())
  File "/Users/laurenpincus/xraylarch/python.app/Contents/lib/python3.9/site-packages/larch/apps.py", line 318, in run_larch
    cli = shell(quiet=args.quiet, with_wx=with_wx)
  File "/Users/laurenpincus/xraylarch/python.app/Contents/lib/python3.9/site-packages/larch/shell.py", line 54, in __init__
    self.larch = Interpreter(with_plugins=with_plugins,
  File "/Users/laurenpincus/xraylarch/python.app/Contents/lib/python3.9/site-packages/larch/interpreter.py", line 136, in __init__
    setattr(mathgroup, fname, getattr(numpy, sym))
  File "/Users/laurenpincus/xraylarch/python.app/Contents/lib/python3.9/site-packages/numpy/__init__.py", line 315, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'loads'
(base) laurenpincus@lnp24mbp2020 ~ % 

I'm on macOS Catalina 10.15.7. I noticed this issue (the applications not opening) before I did the reinstall of Larch using --devel which was why I first removed Larch from the system. 

Thanks,
Lauren

**Comment by maurov** [comment]
Hi @LaurenPincus it seems that in your numpy version there is not the `loads` function. Please, could you give me your numpy version? Activate your `base` conda environment, then `python -c "import numpy; print(numpy.__version__)"`

**Comment by newville** [comment]
@LaurenPincus @maurov Sorry for the trouble.  It looks like `numpy.loads` has been deprecated and might be removed in the latest version.  We were sometimes (but not always!) checking for that scenario.  

I just pushed fixes, removing this and other no-longer-available numpy functions (that we could not have been using!), and updated "load stuff from numpy" to better look for this in the future.

So, I *think* the current master branch should work with fresh installs, but I have not tested that thoroughly.

**Comment by maurov** [comment]
Hi @newville, thanks for the quick fixes, your changes seems fine to me too. @LaurenPincus, could you try reinstalling with the `--devel` option and let us know if it working ?

**Comment by LaurenPincus** [comment]
Hi @newville and @maurov thank you both for your help! So I was able to reinstall the new master version and the XAS viewer will now open.

I'm having another weird issue though where now I can't import files into XAS viewer, either data files from a beamline or  project files from larch. In the case of importing data files I can view the data as usual in the "build arrays" window, but when I click "OK" nothing happens. Similarly in the "read athena" window for importing project files I select the file and then nothing happens when I click "import selected groups". Sorry for all the issues!

**Comment by maurov** [comment]
> I'm having another weird issue though where now I can't import files into XAS viewer, either data files from a beamline or project files from larch. In the case of importing data files I can view the data as usual in the "build arrays" window, but when I click "OK" nothing happens. Similarly in the "read athena" window for importing project files I select the file and then nothing happens when I click "import selected groups". Sorry for all the issues!

Please, can you post the error you should get at the prompt if you start xas_viewer from the shell ?

**Comment by newville** [comment]
@LaurenPincus Sorry - you're definitely now running the "development version", so might be finding recently introduced bugs.  I see the problem and will push a fix shortly....

**Comment by newville** [comment]
@LaurenPincus OK, I think it will work now (to reinstall, that is)

**Comment by LaurenPincus** [comment]
@newville @maurov the current version had a successful install using --devel and now appears to be running well. Thank you again for your help!

**Comment by newville** [comment]
@LaurenPincus  whew!
