### ISSUE TITLE
Small bug- copy function not working in a few places

### ISSUE THREAD

**Issue by LaurenPincus** [xraypy/xraylarch#336]
Hi @newville and @maurov,

Sorry to hop on here again. I'm seeing some small bugs so wanted to report them. I'm having issues with some of the copy functions in Larch. I've seen this issue in a few places: 1. if I have a group selected and want to copy the group (groups --> copy group) no new group appears, 2. in the correct over-absorption window "save as a new group" doesn't work, 3. in the deglitching window "save as a new group" doesn't work.

A separate question that isn't time sensitive, is there a way to add a function to invert data as its imported into Larch? I'm importing some HERFD data from ISS at NSLS II and it needs to be inverted as it's imported. I can do this to each individual spectra by going to add/subtract spectra, having my spectra as "a" and the expression as "-a" and saving that as a new group but it would be great if this was an easy feature to add during import, essentially a third option in the first tab of y array that is just "-".

Let me know if you need further info, thanks!

Lauren

**Comment by LaurenPincus** [comment]
Quick update, I'm now no longer having issues with the "copy to selected groups" button, so just the copy group and save as a new group in the correct over-absorption window.

**Comment by Ardalanhayatifar** [comment]
Hi @LaurenPincus. I hope I got it correctly. You want to inverse the data by putting a minus before them?
I wasn't able to use this part initially to do it:

<img width="772" alt="Screen Shot 2022-01-12 at 11 05 30 AM" src="https://user-images.githubusercontent.com/28695266/149187618-94d77b5c-da10-4fa5-8356-93642af34769.png">

What I did is I added a column of zeros to the data and then did the substraction:



<img width="772" alt="Screen Shot 2022-01-12 at 11 07 31 AM" src="https://user-images.githubusercontent.com/28695266/149187783-f856aa73-695a-40fa-849d-61f69b1b6e65.png">

**Comment by LaurenPincus** [comment]
hi @Ardalanhayatifar, 

Below is the data as its imported. I simply want to invert the spectra which should be accomplished by multiplying by "-" during the import but this currently isn't an option. It's an easy fix within Larch for each individual spectra to go to "add and subtract spectra" and then put "-a" as your expression and save this as your new group. Equally, as you say, it could be changed in the text file prior to import, but it would be great to add the function to the Larch importing interface this way this can happen automatically during the import rather than doing this to each merge file.

<img width="658" alt="Screen Shot 2022-01-12 at 12 11 55 PM" src="https://user-images.githubusercontent.com/97177179/149188734-8d12f765-f5bb-4d08-9dfe-c8cd80b7268d.png">
Here it is after inverting using the "add and subtract spectra":
<img width="553" alt="Screen Shot 2022-01-12 at 12 17 36 PM" src="https://user-images.githubusercontent.com/97177179/149189469-1e4f8fed-fec0-4fcc-9ddf-50aca085d0ec.png">

**Comment by Ardalanhayatifar** [comment]
@LaurenPincus I agree. Perhaps other operations or an expression box can be added here @newville :

<img width="662" alt="Screen Shot 2022-01-12 at 11 29 00 AM" src="https://user-images.githubusercontent.com/28695266/149191477-352c28e5-46fd-4ff9-8ac5-81ba3567e4f4.png">

**Comment by newville** [comment]
@LaurenPincus @Ardalanhayatifar Thanks!

Re: "copy to selected" for normalization.  I have seen (and others have reported) similar issues of "the copy button really didn't work" on occasion too.  I'll look into this again. It seems that it "usually works", meaning that sometimes it does not.   For sure if you change E0 and normalization range and do "copy to selected" of the Normalization parameters, it might reset your E0 to a default value.  That's kind of how it is designed, but I get that it might be good to have a "copy all of the current parameters to the selected groups".  I don't know if that is what you were experiencing.

Re: "copy group" and "save to new group" from the deglitch and over-absorption window.  I thought these worked, but I'll look into these too.

For "invert data on import": adding a "-" sign for inverting on import would be easy enough.  I worry that with just a "-" sign, some people will do -Itrans/I0, without taking the log, but I guess we should allow that. 

But also: it seems odd to me that HERFD data would actually go down.  Are you sure that's correct?

**Comment by LaurenPincus** [comment]
@newville thanks for your help Matt! Yes, at ISS I0 is negative which also makes the HERFD signal negative

**Comment by newville** [comment]
I think this is now much better with 0.9.60.
