### ISSUE TITLE
Fresh installation not working

### ISSUE THREAD

**Issue by Crystal4276** [xraypy/xraylarch#340]
Hello Mauro and Matt,

Happy new year !

I have some issue for starting larch (0.9.58)
I have installed the software following the guidelines : "Installing into an existing Anaconda Python environment"
https://xraypy.github.io/xraylarch/installation.html#install-win.

This is on a computer with a new win10 install followed by a new miniconda install.
All the installation process happen smoothly without any errors.

When I attempt to create the shortcuts with larch -m or try to run xas_viewer launching it from the terminal i get in both case the same sequence of error messages (pasted below).
The "not enough memory resource" at the end sounds weird given that 80 GB RAM are available.

Best,

Samy

Traceback (most recent call last):
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\Scripts\larch.exe\__main__.py", line 4, in <module>
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\larch\__init__.py", line 52, in <module>
    from . import builtins
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\larch\builtins.py", line 27, in <module>
    from . import xrd
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\larch\xrd\__init__.py", line 25, in <module>
    from .amscifdb import CifStructure, get_amscifdb, get_cif, find_cifs
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\larch\xrd\amscifdb.py", line 41, in <module>
    from pymatgen.io.cif import CifParser
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\pymatgen\io\cif.py", line 32, in <module>
    from pymatgen.symmetry.maggroups import MagneticSpaceGroup
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\site-packages\pymatgen\symmetry\maggroups.py", line 9, in <module>
    import sqlite3
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\chikhs\miniconda3\envs\xraylarch\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: Not enough memory resources are available to process this command.

**Comment by newville** [comment]
@Crystal4276 that is very weird.  If this is is an existing Anaconda environment, I'll assume that means you're sort of comfortable with `conda` and `python`.  Can you report the version of `pytmatgen` and Python?   Like, I believe this is really a problem with either `pymatgen`.  It could actually be a problem with `sqlite`, but that's a builtin package.  

I might suggest trying `conda update --all`.

Or try just a plain `import sqlite3` in a Python session.

**Comment by Crystal4276** [comment]
larch was installed on its own conda environnement (not base).
This is the total list of package that was installed via the commands given on Larch website
https://pastebin.com/uDRgB0yU

Python version is 3.8.0
pymatgen version is : 2022.01.09

Conda update -all results in this update :
https://pastebin.com/JB1D5QJp

And after this, it works !!!

One question tough. 
Launching XAS viewer started from the newly created shortcut on desktop  open a terminal window and i can see this message:
No conda env active, defaulting to base

Is there a way to point to the correct env to xraylarch instead of base ?
Does it make any difference when running the program ?

**Comment by newville** [comment]
@Crystal4276 OK, that's good!  It looks like your update did not install a new version of pymatgen (it was labeled 2022.01.09, so apparently very recent!) but did upgrade python from 3.8.0 to 3.8.12.  I suspect that might have been the thing that actually fixed the problem.  Anyway, great!

For which conda environment to use:  I should be fine to run in the "base" environment.  For reasons I don't fully understand, some packages really need to be from some environment, and conda on Windows sort of refuses to have a default environment (apparently assuming that anyone using Anaconda Python will want to understand and handle their package manager).  

I think it would be possible to edit "Scripts\baserunner.bat" and/or "Scripts\xas_viewer.bat" to select a custom environment.  You might have to play around with that.

**Comment by Crystal4276** [comment]
Thanks Matt! 
I will try to tinker with the .bat script.

Maybe  one suggestion for an update of the documentation page  ?
https://xraypy.github.io/xraylarch/installation.html#installing-into-an-existing-anaconda-python-environment
Change:
conda create -y --name xraylarch python==3.8
 by
conda create -y --name xraylarch python==3.8.12

Maybe it will fix it from the start for other users.

Best,

Samy

**Comment by newville** [comment]
@Crystal4276 maybe it would be safer for the docs to suggest `conda update -all`

**Comment by maurov** [comment]
@Crystal4276 thanks for reporting this, I have updated the documentation accordingly.
