### ISSUE TITLE
larch -m not working under macOS Catalina

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#344]
@newville I got a report from a user who is not able to run xas_viewer from the desktop icons under MacOS Catalina 10.15.6.

I recommended using `larch -m` to fix it. The command runs smoothly without errors and no effect at the end.  Nevertheless, the user can correctly run xas_viewer from the terminal once  `$HOME/xraylarch/bin` is added to PATH in `.zshrc`.

I do not have access to any MacOS machine, and no idea how/if you could reproduce this from your side. Anyway, this is not urgent. I put it here just to keep track of it.

**Comment by newville** [comment]
@maurov thanks.  "larch -m" works for me on MacOS Monterey (and using zsh as the default shell).  I doubt that Catalina would actually be different  - it did work for me, and I don't know what would have changed there.  

Feel free to have that user contact me, either here or by email.

**Comment by maurov** [comment]
@newville this is a low priority thing, because the user can run xas_viewer from the terminal. So I close the issue.

Anyway, if you are curious to dig it more, it seems that the other applications launch correctly, while xas_viewer not. I put here the  [Larch directory](https://github.com/xraypy/xraylarch/files/7959392/Larch.zip), but I do not see anything different in the bash scripts.

**Comment by newville** [comment]
@maurov Thanks - that's really odd.  All of those look OK, but the bash script has what looks like sort of recursive settings for paths, like
```
export PYTHONEXECUTABLE=/Users/blanchecollin/xraylarch/python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../bin/python
export EXE=/Users/blanchecollin/xraylarch/python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/../../../python.app/Contents/MacOS/python
```

I don't see that, but maybe that is the problem (or the path is too long?).  I'll see if it is easy to fix that.
