### ISSUE TITLE
LCF using flattened data 

### ISSUE THREAD

**Issue by LaurenPincus** [xraypy/xraylarch#346]
Hi @newville,

Quick question. Within Larch is there a way to do LCF with flattened data? I only see an option to use normalized u(E), raw u(E), du(E)/D(E), and x(k).
<img width="638" alt="Screen Shot 2022-01-27 at 10 51 23 AM" src="https://user-images.githubusercontent.com/97177179/151565619-7ca96eb6-0212-4b30-8e87-e92e6cdcb318.png">

I know within Athena the documentation states "The fitting is done using the normalized μ(E) spectra. If the standards or the unknown are to be flattened, then the flattened spectrum will be used. (See the section on background removal for details about flattened spectra.)" I was curious if this is the case for Larch as well. 

If this is not already a feature would it be possible to add this? 

Thanks,
Lauren

**Comment by newville** [comment]
@LaurenPincus Ah, good point.  I will fix this.

**Comment by maurov** [comment]
@newville should we allow to use flattened data in LCF/PCA analysis? This was an old question: #44 (and also somehow popped out in #351 recently). Should we post this question on the Ifeffit mailing-list?

**Comment by newville** [comment]
@maurov I'm OK with making sure that 'flattened' is an option for all the XANES analysis panels / routines.  I think it is not currently uniformly supported, but I'll (try to!) make that change for 0.9.59.

**Comment by newville** [comment]
fixed in 0.9.60
