### ISSUE TITLE
Flattened Data

### ISSUE THREAD

**Issue by pattammattel** [xraypy/xraylarch#351]
https://github.com/xraypy/xraylarch/blob/888eee5813fa85dd03b79942427d0c6693555441/larch/xafs/pre_edge.py#L3

Hi @newville, I was trying to use flattened data in an NSLS-II software. I am using the `pre_edge` function. The output of 'norm' and 'flat' was the same for the data. So I did some debugging here
 ` flat = norm - (flat_diff  - flat_diff[ie0])
        #print(f" Flattened calc {flat}")
        #print(f" Normalized {norm}")
        flat[:ie0]  = norm[:ie0]
        #print(f" Flattened end {flat}")`

I am not sure why you do `flat[:ie0]  = norm[:ie0]` at the end. I am using 0.9.57. 

##Results 

Flattened calc [0.18568206 0.15896598 0.13545524 0.12651269 0.11065022 0.10055501
 0.09416831 0.09455091 0.08546941 0.07931232 0.08010499 0.0996874
 0.108231   0.09651713 0.08940077 0.08752898 0.10104972 0.1329587
 0.22340007 0.39127195 0.67447672 1.0153617  1.39513717 1.72465985
 2.01901721 2.20563692 2.34261249 2.3017053  2.0762852  1.82643005
 1.71037294 1.67104732 1.54768914 1.40183244 1.35360824 1.29542405
 1.26664091 1.25057488 1.23779892 1.21839927 1.18220579 1.15114975
 1.09193189 1.04601965 0.98791269 0.93011594 0.89209293 0.90114108
 0.91546277 0.91612148 0.95399258 0.98065518 1.01673639 1.0680706
 1.08615576 1.06244119 1.04605427]
 Normalized [ 3.16716243e-03 -9.37458010e-04 -2.89446212e-03  7.55470297e-03
 -2.56675643e-03 -5.59713133e-03 -5.75720057e-03  1.73679892e-03
 -8.65270052e-04 -6.49372168e-04  6.80898636e-03  3.30970061e-02
  4.82264654e-02  4.30785045e-02  4.32132461e-02  4.79406224e-02
  6.81337110e-02  1.06448936e-01  2.03735612e-01  3.77933916e-01
  6.68196871e-01  1.01536170e+00  1.40193591e+00  1.73806441e+00
  2.03924047e+00  2.23247930e+00  2.37574138e+00  2.34190568e+00
  2.12273216e+00  1.87976889e+00  1.77038412e+00  1.73747140e+00
  1.62119802e+00  1.48190058e+00  1.44016245e+00  1.38892336e+00
  1.36675934e+00  1.35714613e+00  1.35113564e+00  1.33840834e+00
  1.30870093e+00  1.28407776e+00  1.23183159e+00  1.19995589e+00
  1.15634449e+00  1.11171281e+00  1.08894373e+00  1.11094407e+00
  1.14016045e+00  1.15399754e+00  1.20633094e+00  1.24689037e+00
  1.28986346e+00  1.36181342e+00  1.39996883e+00  1.39517365e+00
  1.40002780e+00]
 Flattened end [ 3.16716243e-03 -9.37458010e-04 -2.89446212e-03  7.55470297e-03
 -2.56675643e-03 -5.59713133e-03 -5.75720057e-03  1.73679892e-03
 -8.65270052e-04 -6.49372168e-04  6.80898636e-03  3.30970061e-02
  4.82264654e-02  4.30785045e-02  4.32132461e-02  4.79406224e-02
  6.81337110e-02  1.06448936e-01  2.03735612e-01  3.77933916e-01
  6.68196871e-01  1.01536170e+00  1.39513717e+00  1.72465985e+00
  2.01901721e+00  2.20563692e+00  2.34261249e+00  2.30170530e+00
  2.07628520e+00  1.82643005e+00  1.71037294e+00  1.67104732e+00
  1.54768914e+00  1.40183244e+00  1.35360824e+00  1.29542405e+00
  1.26664091e+00  1.25057488e+00  1.23779892e+00  1.21839927e+00
  1.18220579e+00  1.15114975e+00  1.09193189e+00  1.04601965e+00
  9.87912692e-01  9.30115942e-01  8.92092933e-01  9.01141083e-01
  9.15462768e-01  9.16121478e-01  9.53992582e-01  9.80655178e-01
  1.01673639e+00  1.06807060e+00  1.08615576e+00  1.06244119e+00
  1.04605427e+00]

**Comment by newville** [comment]
@pattammattel Yep,  that is intentional.  `flat` and `norm` should be the same up to E0, and differ by a quadratic polynomial above E0.  So, where is E0 in this data?

FWIW, I would never recommend using `flat` for anything except visualization, but some people seem to like to use it in some cases of linear analysis.

**Comment by pattammattel** [comment]
@newville. That explains it. The difference was not obvious in the plotter I was using in the GUI. I could see the changes on excel. Thank you for the quick reply.

Sure, I barely use flattened data but one of the users wanted to fit the flattened spectrum (I saw Lauren already raised that issue) in our program for 2D XANES (https://github.com/NSLS-II/xmidas). 

Ajith

**Comment by newville** [comment]
@pattammattel  OK.  I'm sure code for 2D XANES could be useful for many people.  I totally understand wanting to write your own, but you might also consider whether it would make sense to include that into a large ecosystem, say, like Larch.

**Comment by pattammattel** [comment]
@newville I would love to do that. That could solve some of our issues with sharing it with the users. I will discuss it with Yong Chu, my manager, and Ryan Tappero (he got the funding to develop the program). Thanks

Ajith

**Comment by newville** [comment]
@pattammattel I suggest moving to email, maybe trying to set up a meeting sometime in the next few weeks.

**Comment by maurov** [comment]
@pattammattel I close this issue about the flattened data and let you continue discussing separately with @newville regarding your 2D XANES code. If you still need help about the flattened data, feel free to reopen this issue.
