### ISSUE TITLE
XAS viewer won't open

### ISSUE THREAD

**Issue by LaurenPincus** [xraypy/xraylarch#352]
Hi @newville ,

I'm unfortunately having an issue again where XAS viewer won't open. The application starts to open and then exits itself. I tried removing larch and installing again. The binary installer gives me an error so I installed using the -devel option in the getlarch.sh script in terminal. I don't get any errors during the installation using the script but still XAS viewer won't open. Let me know what other information would be helpful. I've attached my installation log here

Thanks,
Lauren

[GetLarch.log](https://github.com/xraypy/xraylarch/files/8072988/GetLarch.log)

**Comment by LaurenPincus** [comment]
@newville it appears to be an issue with the desktop shortcut. I can open XAS viewer using terminal and typing xas_viewer

**Comment by LaurenPincus** [comment]
@newville I tried deleting the larch folder on the desktop and running larch -m from terminal and this didn't solve the issue. I tried attaching the zip file here, but I'll also send it to you via email. @maurov  yes, I too am running in Catalina 10.15.7.

Thanks! 
[XAS Viewer.zip](https://github.com/xraypy/xraylarch/files/8080966/XAS.Viewer.zip)

**Comment by newville** [comment]
@maurov I agree that it could be related to #344.  I did push a release of `pyshortcuts` which *might* have fixed that (at least, it should shorten convoluted paths) and which was used according to the install log.   But that's also why I asked for the zip file of the App if it is still happening or if something else is going wrong.

**Comment by LaurenPincus** [comment]
I tried  /Users/laurenpincus/xraylarch/python.app/Contents/MacOS/python  /Users/laurenpincus/xraylarch/bin/xas_viewer in terminal and that works fine opening the program as does xas_viewer. 

Typing in which xas_viewer gives the following: /Users/laurenpincus/xraylarch/bin/xas_viewer

I'm running 0.9.58 I believe. I downloaded and installed yesterday using the -devel option.

**Comment by newville** [comment]
@LaurenPincus OK, that all sounds like what I would expect and makes it even more mysterious that the App doesn't work.  
From a Terminal, does 
```
open -a ~/Desktop/Larch/XAS\ Viewer.ap
```

work?

**Comment by LaurenPincus** [comment]
@newville No, that gives the following error: FSPathMakeRef(/Users/laurenpincus/Desktop/Larch/XAS Viewer.ap) failed with error -43.

**Comment by newville** [comment]
@LaurenPincus oh, wait that should be 
```
open -a ~/Desktop/Larch/XAS\ Viewer.app
```

**Comment by Ardalanhayatifar** [comment]
@LaurenPincus You can check your default shell when you open a terminal window. Or by ```echo $SHELL``` command.
You can see them using ```nano ~/.zshrc``` or ```nano ~/.bashrc```.
Also when I use ```which python``` command in Terminal I get:

```/Users/ardalan/xraylarch/bin/python```

What do you get?

**Comment by LaurenPincus** [comment]
@Ardalanhayatifar typing nano ~/.zshrc I get the following: 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/laurenpincus/xraylarch/bin/conda' 'shell.zsh' 'hook' 2$
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/laurenpincus/xraylarch/etc/profile.d/conda.sh" ]; then
        . "/Users/laurenpincus/xraylarch/etc/profile.d/conda.sh"
    else
        export PATH="/Users/laurenpincus/xraylarch/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

**Comment by Ardalanhayatifar** [comment]
@LaurenPincus what about ```which python``` and ```echo $PATH```?

Mine shows that xraylarch is in the PATH:

```
(base) ardalan@Ardalans-MBP ~ % which python
/Users/ardalan/xraylarch/bin/python
(base) ardalan@Ardalans-MBP ~ % echo $PATH
/Users/ardalan/xraylarch/bin:/Users/ardalan/xraylarch/condabin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/ardalan/.rvm/bin

```

**Comment by LaurenPincus** [comment]
@Ardalanhayatifar 

(base) laurenpincus@lnp24mbp2020 ~ % which python
/Users/laurenpincus/xraylarch/bin/python
(base) laurenpincus@lnp24mbp2020 ~ % echo $PATH
/Users/laurenpincus/xraylarch/bin:/Users/laurenpincus/xraylarch/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

**Comment by vaschoepfer** [comment]
Hi @newville I've been having the same issue, and I'm on a (university-controlled) Windows computer. The black box pops up when I click the icon for any of the Larch programs, but it closes immediately and the program I wanted doesn't actually open. I re-downloaded Larch yesterday and re-installed it to C:\Users\vas481\larch today and it still doesn't work.

Before getting IT involved and completely reinstalling it, I also tried to update using the following command, and it seems to have an issue with the program GSAS-II for XRD data.

C:\Users\vas481>pip install --upgrade xraylarch
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\commands\install.py", line 258, in run
    isolated_mode=options.isolated_mode,
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\commands\install.py", line 604, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\commands\install.py", line 549, in site_packages_writable
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\commands\install.py", line 549, in <genexpr>
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\utils\filesystem.py", line 140, in test_writable_dir
    return _test_writable_dir_win(path)
  File "C:\Programs\gsas2full\lib\site-packages\pip\_internal\utils\filesystem.py", line 153, in _test_writable_dir_win
    fd = os.open(file, os.O_RDWR | os.O_CREAT | os.O_EXCL)
PermissionError: [Errno 13] Permission denied: 'C:\\Programs\\gsas2full\\Lib\\site-packages\\accesstest_deleteme_fishfingers_custard_n91r1f'

**Comment by newville** [comment]
@vaschoepfer I think that's a different issue.  The issue here seems pretty specific to the MacOS desktop apps.

What you are seeing looks like a permissions issue, that you won't have write permission to some folder.  I don't think that has anything to do with larch, actually, but something to do with GSAS-II.   Please open a new issue, and don't jump in on an existing issue.   But also, start with a fresh install and then explain what didn't work.

**Comment by newville** [comment]
@LaurenPincus Sorry for the delay on this, but I do have a slight update on this issue. I saw this on another user's Macbook: running `xas_viewer` worked from the command-line, but not the App.  I think I understand this as a permission issue (specific to Mac running as an App).  So, I'm hopeful that this will be fixed in the next release, and I hope this will be soon...

**Comment by LaurenPincus** [comment]
Hi @newville and @maurov I just updated my Larch version to the latest release and am now having the same issue where XAS viewer won't open. However, now I can no longer open the application via terminal either, I get the following error:

Traceback (most recent call last):
  File "/Users/laurenpincus/xraylarch/bin/xas_viewer", line 8, in <module>
    sys.exit(run_xas_viewer())
  File "/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/larch/apps.py", line 127, in run_xas_viewer
    from larch.wxxas import XASViewer
  File "/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/larch/wxxas/__init__.py", line 1, in <module>
    from .taskpanel  import TaskPanel, FONTSIZE
  File "/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/larch/wxxas/taskpanel.py", line 16, in <module>
    from larch.wxlib import (BitmapButton, SetTip, GridPanel, FloatCtrl,
  File "/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/larch/wxlib/__init__.py", line 51, in <module>
    from . import larchframe
  File "/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/larch/wxlib/larchframe.py", line 16, in <module>
    from wxutils import (MenuItem, Font, Button, Choice, panel_pack)
ImportError: cannot import name 'panel_pack' from 'wxutils' (/Users/laurenpincus/xraylarch/lib/python3.9/site-packages/wxutils/__init__.py)

Thanks!

**Comment by newville** [comment]
@LaurenPincus Very sorry for the problem.   I think that what you need to do is open a Shell terminal and do

   C:\Users\laurenpincus\xraylarch\Scripts\pip install --upgrade xraylach



For completeness, this is a serious bug on Windows, and is basically that Windows does not allow an executable program to be replaced while it is open.   I think I have a fix for it in the latest devel version -- basically providing a Shortcut that runs that `pip install` and having the "upgrade ready" message from XAS Viewer say to use that.   Unfortunately, the **current release** still has this problem, so we'll have to be careful about instructing people on this next time too!

**Comment by LaurenPincus** [comment]
@newville Thanks for the quick reply! Just to be clear for your documentation of this issue, I'm running on a mac with OS Ventura 13.3. I do know one issue that may be contributing that we'd discussed previously may be having to do with administrative permissions, the login that I mainly use does not have administrative permissions. 

Would you mind explaining how to open a Shell terminal? I'm familiar with the process of opening a powershell window on Windows, but am not sure how to do so for OSX.

Thanks!

**Comment by newville** [comment]
@LaurenPincus Sorry, I think I gave too quick of a reply earlier.  

To open a Terminal on MacOS, you go to Applications->Utilities->Terminal.app

But now that I look at your report more carefully, I think that all you should need to do at that Terminal is then

```     
  /Users/laurenpincus/xraylarch/bin/pip install --upgrade wxutils xraylarch
```

**Comment by LaurenPincus** [comment]
@newville Yes, that worked, thank you very much!
