### ISSUE TITLE
Use `energy_shift` variable instead of rewriting the `energy` array on recalibration

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#357]
@newville I propose (based on feedbacks from users too) to **modify the behaviour of the energy calibration procedure**. Currently, the original `energy` array is overwritten when doing the energy recalibration. Instead of this, I propose to use `energy_shift` attribute in the group object (with default value of 0) and use it to get the correct energy array. What about the following:

- init `Group` with `_energy` and `energy_shift=0`
- decorate `Group.energy` with a getter in order to return `self._energy+self.energy_shift`
- energy recalibration will only affect `energy_shift`

If ok with this behaviour, we could then add the "Energy shift" value in the GUI, below the "Energy Reference Group" combo box. This behaviour mimics the one in Athena.

**Comment by newville** [comment]
@maurov is the idea that one would want to undo (and not just "redo") the energy shift?  Like, when would ever use "energy" and not "energy+energy_shift"? 
Would it be OK to save "energy_shift" with the opposite sign if/when the energy is re-calibration, so that "restore original energy" could be done?  But then, that should probably be exposed in the GUI somehow, maybe near the bottom of the Normalization Panel.

**Comment by maurov** [comment]
@newville the idea is to always return `group.energy = group._energy + group.energy_shift` (energy shift could also be negative). To go "back to original" one has simply to put `group.energy_shift=0`. Yes, the energy shift variable should be exposed in the GUI at the bottom of the normalization panel.

**Comment by newville** [comment]
@maurov  My view is that using `group.energy` array is a lot more common than changing the calibration.  If we had to use `group.energy + group.energy_shift` everywhere in the code, that would mean a lot of continued vigilance and it would be very easy to miss someplace.

If someone wants to change the calibration, that's fine, and exposing that on the normalization panel is fine.  I'd just rather save and keep track of an "energy_orig" array of the original energy or an "energy_shift" number to return to the original, but actually set "energy" to be the energy array to use.

**Comment by maurov** [comment]
@newville I am not proposing to replace `group.energy` in the code, but at the definition of the `Group` class. Something like:

```python
    @property
    def energy(self):
        return self._energy + self.energy_shift

    @energy.setter
    def energy(self, energy_array):
        self._energy = energy_array
        self.energy_shift = 0  
```
What do you think?

Otherwise it is also fine with me to keep `energy_orig` and `energy_shift` and when the user changes the energy_shift value in the GUI, then `group.energy` is rewritten.

The advantage of having this logic at the Group level is that is independent of the GUI, but I let you choose.

**Comment by newville** [comment]
I think this is now working much better....

**Comment by newville** [comment]
@maurov Oh, I never noticed that was how Athena worked.  I would think it would be better to be a deliberate step, but maybe giving a message that it shifted other groups too?

**Comment by maurov** [comment]
> @maurov Oh, I never noticed that was how Athena worked. I would think it would be better to be a deliberate step, but maybe giving a message that it shifted other groups too?

Well, if a group is linked to an "energy reference group", I think it is expected that applying an energy shift in the energy reference group, it should go to the linked group too. I am not against adding a message in the information bar (a pop up window may be too much).

**Comment by newville** [comment]
@maurov Yeah, I guess that is a reasonable behavior - if you go to the trouble to setting a reference, that is probably what you meant, and it can be undone.  Adding that now, so that energy shifts are copied to groups sharing a reference -- and a preference to turn that off.
