### ISSUE TITLE
Read File Error

### ISSUE THREAD

**Issue by Ardalanhayatifar** [xraypy/xraylarch#359]
I’m having trouble opening the data file containing multiple columns. The error I get:

```Cannot read /Users/ardalan/OneDrive - University of Saskatchewan/Elliot/examples/129_1.dat  
Error trying to read '/Users/ardalan/OneDrive - University of Saskatchewan/Elliot/examples/129_1.dat':

_tmp_file_ = read_xdi('/Users/ardalan/OneDrive - University of Saskatchewan/Elliot/examples/129_1.dat')
^^^
File /Users/ardalan/.larch/init.lar, line 1
File "/Users/ardalan/xraylarch/lib/python3.8/site-packages/larch/closure.py", line 76, in __call__
return self.func(*args, **kwds)
File "/Users/ardalan/xraylarch/lib/python3.8/site-packages/larch/io/xdi.py", line 252, in read_xdi
xdif = XDIFile(filename, labels=labels)
File "/Users/ardalan/xraylarch/lib/python3.8/site-packages/larch/io/xdi.py", line 112, in __init__
self.read(self.filename)
File "/Users/ardalan/xraylarch/lib/python3.8/site-packages/larch/io/xdi.py", line 129, in read
raise ValueError(msg)

ValueError: Error reading XDIFile /Users/ardalan/OneDrive - University of Saskatchewan/Elliot/examples/129_1.dat
non-numeric value in data table
```

I’ve attached the file:
[129_1 copy.txt](https://github.com/xraypy/xraylarch/files/8328212/129_1.copy.txt)

**Comment by newville** [comment]
@Ardalanhayatifar for me, that file gives an error message ending with
```
  File "/Users/Newville/xraylarch/lib/python3.9/site-packages/xraylarch-0.9.58.post93+g4004e563.d20220320-py3.9.egg/larch/io/xdi.py", line 129, in read
    raise ValueError(msg)

ValueError: Error reading XDIFile x129_1.xdi
one or fewer rows in data table
``` 

which might be a little more helpful: there is one line of actual data.

I would also be cautious about using a file with that many columns.  XDI will definitely ignore columns past 128, and may give many error messages about that.  Have you verified that other such files do, in fact, work?   

All that said, it seems reasonable for XAS Viewer to  detect an error from `read_xdi()` and then try a plain `read_ascii()`, which is not as complete, and does not attempt to read meta-data, but in this case would actually read successfully, and likely indicate that the file only has one row.

**Comment by Ardalanhayatifar** [comment]
Thanks for checking it out. I reduced the files and columns and got to:

```metadata not formatted as Family.Key: Value```

I looked at .xdi format [documentation](https://github.com/XraySpectroscopy/XAS-Data-Interchange/blob/master/specification/spec.md) and the problem is now fixed when I removed the the first line of the file:

```# XDI/1.0```

It works fine now.

**Comment by newville** [comment]
@Ardalanhayatifar 

That is really weird. I definitely do not get that error with the file you posted either.  And I'm pretty sure the XDI reader has not changed in a while.  But your file didn't have any data in it.    So, either you're not telling me everything you did or something is very broken with your installation.

For sure, if you edit a file by hand, you can break the XDI format.  But why would you do that?   And, for sure, if you do edit a file by hand, the only reasonable response I can give is "well, if you broke it, you're going to have to figure out how to fix it".

**Comment by Ardalanhayatifar** [comment]
Here is the full original data file. It gives the previous error when the first line is not removed but works fine when the first line is removed.

[129_1.dat.txt](https://github.com/xraypy/xraylarch/files/8336309/129_1.dat.txt)

**Comment by newville** [comment]
@Ardalanhayatifar Thanks for an actual example. Yeah, I think it is failing because it has more than 128 columns.   I will have XAS_Viewer look for such errors and try to read with "read_ascii()", which does work.

I could also switch to reading XDI files with pure Python, which would alleviate the problem. The original goal for XDI was to have something cross-platform, documented, and with multiple implementations based on the reference C code. We stuck with that approach for a while, but it has not really gained traction and maybe we should just read it with Python.  One fewer C library to support...
