### ISSUE TITLE
Cannot open project

### ISSUE THREAD

**Issue by AnnaDragonfly** [xraypy/xraylarch#360]
Hi Matt @newville ,
I'm using Larch for some time. Everything worked fine until this weekend. I can use XASviewer to process data however I can't open any of the saved projects. When I try to open the saved project, I got error message in the terminal (see below) and the project has not been opened. I also tried to load new data and saved as a new project - l also couldn't open it. Any ideas how to fix it?

# run in conda environment "base":
# c:\users\annaw\xraylarch\Scripts\xas_viewer.exe
Traceback (most recent call last):
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\wxxas\xasgui.py", line 799, in onReadDialog
    self.onRead(path)
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\wxxas\xasgui.py", line 809, in onRead
    self.show_subframe('athena_import', AthenaImporter,
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\wxxas\xasgui.py", line 754, in show_subframe
    self.subframes[name] = frameclass(self, **opts)
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\wxlib\athena_importer.py", line 83, in __init__
    self.a_project = read_athena(self.filename, do_bkg=False, do_fft=False,
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\io\athena_project.py", line 915, in read_athena
    aprj.read(filename, match=match, do_preedge=do_preedge, do_bkg=do_bkg,
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\io\athena_project.py", line 780, in read
    data = parse_perlathena(text, self.filename)
  File "c:\users\annaw\xraylarch\lib\site-packages\larch\io\athena_project.py", line 353, in parse_perlathena
    raw[key] = np.array([float(x) for x in aeval(text2list(t))])
  File "c:\users\annaw\xraylarch\lib\site-packages\asteval\asteval.py", line 314, in __call__
    return self.eval(expr, **kw)
  File "c:\users\annaw\xraylarch\lib\site-packages\asteval\asteval.py", line 324, in eval
    raise ValueError(msg)
ValueError: length of text exceeds 50000 characters[]
![issue](https://user-images.githubusercontent.com/102514257/160361492-12e973fa-a7d6-4e02-9e35-a014a64d6d47.png)

Best,
Anna

**Comment by newville** [comment]
@AnnaDragonfly Oh, yes, very sorry for the trouble - this has been seen and is fixed in the development version.  I think it is probably time to release a "0.9.59" very soon with this and several other bug fixes.

**Comment by AnnaDragonfly** [comment]
Hi Matt, Thanks for the quick reply. Is there any option to temporarily work around this bug?
Thanks for speeding up to release new version.
Anna

**Comment by newville** [comment]
@AnnaDragonfly How comfortable are you with using command-line and Python?  It would be downloading a zip file, opening a command terminal and typing a few commands...

**Comment by AnnaDragonfly** [comment]
@newville I should be able to handle it :)

**Comment by maurov** [comment]
@newville I got the same issue reported from a couple of users under Ubuntu 20.04 and Mac, using Larch 0.9.58 and asteval 0.926. I confirm this does not happen in the current development version. Please, do you know from where it comes this bug?

**Comment by newville** [comment]
@maurov yeah, it is solved (or, well, vastly improved).   What happened was that over at `asteval`, someone noticed that a very long statement (like, 80,000 characters like '()()()()....') could crash Python.  So we set a default maximum to 50,000 characters per statement. But, reading Athena Project files evaluates the strings, and some of those (especially "journals") can be very long.  So the default for reading athena files is now 12,500,000 characters *per statement* and journals are allowed to fail.

@AnnaDragonfly if you download
   https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl

and then open an "Anaconda (xraylarch)" command terminal (should be under "Anaconda Python" in your start menu), you should be able to find this file (probably in "downloads") and do

    pip install xraylarch-latest-py3-none-any.whl

That *should* work, but please let me know how it goes.  If that works OK, maybe we should make that "latest wheel" updated more often and use this approach as a "get devel version".

**Comment by maurov** [comment]
> @maurov yeah, it is solved (or, well, vastly improved). What happened was that over at `asteval`, someone noticed that a very long statement (like, 80,000 characters like '()()()()....') could crash Python. So we set a default maximum to 50,000 characters per statement. But, reading Athena Project files evaluates the strings, and some of those (especially "journals") can be very long. So the default for reading athena files is now 12,500,000 characters _per statement_ and journals are allowed to fail.

@newville I also confirm that larch devel + asteval 0.9.26 works. larch 0.9.58 + asteval 0.9.26 fails, while larch 0.9.58 + asteval 0.9.19 works too (at least with the Athena project file I am using as test). What about if for a given larch release we stick to a given asteval version?

**Comment by newville** [comment]
@maurov Yeah, I think "asteval changes break larch" will be unusual.  We do specify a minimal version (and so does lmfit), but making sure that "latest" works is also important because a fresh install will grab the latest.

So, yeah, I did just specify lmfit 1.0.3 and asteval 0.9.26 in requirements.txt.
