### ISSUE TITLE
coordinate release 0.9.60

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#362]
@newville I put here notes/summary that I will update during development to keep track of what was added/modified/fixed

**WIP, partially adressed:**
- #329
- #334
- #336
- #347
- #352
- #357

**Proposed (ordered by priority?):**
- #363 
- better expose all of the mapping of displayed spectra "filename" to "groupname" within Larch.
- allow editing of CIFs
- XRF Fitting with finite matrix effects.
- #336 
- test Linux binaries under Ubuntu 20.04
- why pymatgen is not pip-installable?
- make a "daily built wheel" available. This should be feasible directly with Github, if I am not wrong
- may consider moving to [semantic versioning](https://semver.org/) or simply stick to a "date-like" versioning (e.g. YYYY.MM).

**Added:**

- #326 
- #356 

**Modified:**

**Fixed:**

- #368 
- #369 
- #346

**Comment by newville** [comment]
@maurov thanks!!   I'm actually thinking that we might just want to call some version 1.0.0 pretty soon.... I think we know that most of the basic code is pretty stable and that the earlier approach with "plugins" and an emphasis on "mini language" is pretty much gone.   I also think that the XAS Viewer (and XRF analysis) is "mostly there" and at the point of feature fixes. 

That is,  I think the near-term to-do list (say. for 0.9.60):

1. Larch Project File in HDF5 (and/or Zarr, which I'm interested in for XRF maps too) which saves all the analysis components (pre-edge, PCA, Feff-fit, XRF, etc) fitting models and results history.
2. Better expose all of the mapping of displayed spectra "filename" to "groupname" within Larch.
3. allow editing of CIFs
4. XRF Fitting with finite matrix effects.

looks a lot like a list for 1.0.0

**Comment by maurov** [comment]
>     1. Larch Project File in HDF5 (and/or Zarr, which I'm interested in for XRF maps too) which saves all the analysis components (pre-edge, PCA, Feff-fit, XRF, etc) fitting models and results history.

@newville yes, this is definitively top priority -> #363

**Comment by maurov** [comment]
@newville I am sorry, but I have lost track of your huge work done lately on saving the Larch project files. Do you think it is possible to release `0.9.60` soon? By the end of next week?

**Comment by newville** [comment]
@maurov Yes.  I had been hoping for "today", but I still have a couple of things I would like to fix.  And the documentation is way behind.   So, I'm now hoping for Monday.  I'm expecting to release this to generate suggestions and find critical problems that I missed, that need a 0.9.61 release within a month.    So, these changes need some explanation and allow for comments/suggestions.

Significant changes are:

**Project/Session File**: this saves the full session, including all the arrays (not just mu(E) and the analysis parameters), fitting models, and the fit histories for pre-edge peak fitting, linear combinations, and Feff fitting (including the Feff Paths). Getting this to work and having the results reloaded into XAS_Viewer meant some real changes to the GUI code, and also changes to some of the non-GUI code: not really the analysis steps, but maybe how the data structures were laid out.  Anyway, I think this is working, if only "beta" or "version 1".    The file format is "Gzipped blob with json-encoded objects".  It is worth discussing other options, like HDF5 (which could be a lot of work and still end up with lots of "json-encoded" strings), but we should decide on this within a few releases (or, say 1 year) so existing format could be converted without needing to support multiple versions for very long.

**Journal**: added a Journal for each group, timestamping the major processing steps.  This can be viewed and added too, and journals are saved in the Project files...   Many of the "callargs" have been moved to a single group.

**Preferences**:  GUI form for editing preferences for settings and form values (most of these are actually used, most of the time!!!), can be saved and then autoloaded for future sessions.  Each group will have a configuration, using these as defaults, and "copy to all groups" is much better at updating a group's config, but not the default preferences.

**Energy shifts**.  These are handled much better, and the calibration dialog can either shift the actual energy or just record what the "energy shift" for each group should be -- that allows "energy shifts" to be re-done and un-done more easily.  Energy re-binning is also much better.

For the list of priorities, 

- Done, I think: Larch Journal
- Done: better expose all of the mapping of displayed spectra "filename" to "groupname" within Larch.
- Not Done: allow editing of CIFs
- Work in Progress: XRF Fitting with finite matrix effects.
- Fixed, I thnk:  copy function acting weird sometimes.
- Not Done: test Linux binaries under Ubuntu 20.04
- Not Sure: why pymatgen is not pip-installable?
- Sort of:  make a "daily built wheel" available. This should be feasible directly with Github, if I am not wrong. (that is, it is at https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl)
- Not Done: may consider moving to [semantic versioning](https://semver.org/) or simply stick to a "date-like" versioning (e.g. YYYY.MM).

**Comment by maurov** [comment]
@newville thanks for your great work on this release ! I close this now.

**Comment by newville** [comment]
@maurov Thanks -- hopefully the number of serious bugs will be small!
