### ISSUE TITLE
deglitch & calibrate energy

### ISSUE THREAD

**Issue by duoduoss** [xraypy/xraylarch#364]
@newville 
Thank you very much for the new version and all updating!  

Through my practice on XASViewer, I had these issues on the deglitch and energy calibration: 

1.  The pointer selecting for deglitching is the previous style. Sometimes, after removing points and being saved as a new file, the new file was listed there but could not be used. On the terminal there were error messages
"Traceback (most recent call last):
  File "c:\programdata\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 484, in onPlotOne
    self.plot(self.controller.get_group())
  File "c:\programdata\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 977, in plot
    self.get_plot_arrays(dgroup)
  File "c:\programdata\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 939, in get_plot_arrays
    self.process(dgroup=dgroup, force=True)
  File "c:\programdata\xraylarch\lib\site-packages\larch\wxxas\xasnorm_panel.py", line 747, in process
    ediff = (e1 - e2).min()
ValueError: operands could not be broadcast together with shapes (347,) (356,)" 

2. In the energy calibration, when I tried to select a point, nothing happened with error message: 
"TypeError: on_select() got an unexpected keyword argument 'name'"

In addition, is it possible to change the time delay for the point selection? For example, from the current 3 seconds to 0.5 s?

**Comment by newville** [comment]
@duoduoss sorry for the trouble and thanks for the report.  I see those too, and will try to fix them soon!

**Comment by duoduoss** [comment]
@newville 
Yes, by installing the development branch they are all fixed. And I also notice the point selection becomes fast faster, which is very convenient. 
Thank you very much!

**Comment by newville** [comment]
fixed for 0.9.60
