### ISSUE TITLE
[xas_viewer] current group highlight does not stay persistent

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#368]
@newville I have observed an annoying behavior on xas_viewer (master on Linux) that seems a bug to me:

- click on a group -> it gets highlighted in the left panel
- push the plot button -> the highlight disappears

Can you reproduce this misbehavior from your side?

**Comment by newville** [comment]
@maurov I do see that the "current group" loses its color on Linux... will investigate, but it might be an underlying widget problem....

**Comment by newville** [comment]
@maurov I think this is now fixed -- at least for me on one Linux system ;).  Some wx GUI stuff is just weird!

**Comment by maurov** [comment]
@newville thanks for fixing it. I confirm now it works as expected.

**Comment by maurov** [comment]
@newville I reopen this issue because this bug shows again in the latest version in master.

**Comment by newville** [comment]
@maurov  I see this as not being very consistent -- sometimes the current group is highlighted and sometimes not.  I'm not seeing much of a pattern to that.

**Comment by maurov** [comment]
@newville I confirm this misbehavior is persistent under Ubuntu 20.04, the Linux OS of choice here at ESRF and rather common Linux OS worldwide. I have the feeling that, since conda is built under CentOS Linux, there is a serious issue having wxPython correctly working under Ubuntu Linux.

**Comment by newville** [comment]
@maurov Yeah, I see this on Fedora 30-something too.  I think it worse than "built on CentOS, run on Ubuntu".  I think that the  "keep focus color" on those windows is just being lost when you click on another window, and that it is something at the level of how wx interacts with Gtk.

**Comment by newville** [comment]
@maurov I think this might actually be better now.  I am more aggressively moving "Focus" back to the List of Files after each plot.  For me on Fedora 34, this seems much better.  

I'm running a few more tests, but hoping to tag and release 0.9.63 later today or tomorrow...
