### ISSUE TITLE
pycifrw problem

### ISSUE THREAD

**Issue by dxfan2022** [xraypy/xraylarch#369]
There are error for pycifrw, do I need care this problem?  do I installed Larch in Anaconda successfully?

Building wheel for pycifrw (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\anaconda3\envs\xraylarch\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Dongxiao FAN\AppData\Local\Temp\pip-wheel-5g7b2r0q'
       cwd: C:\Users\Dongxiao FAN\AppData\Local\Temp\pip-install-40e_mgd2\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\CifFile
  copying src\__init__.py -> build\lib.win-amd64-3.8\CifFile
  copying src\CifFile_module.py -> build\lib.win-amd64-3.8\CifFile
  copying src\yapps3_compiled_rt.py -> build\lib.win-amd64-3.8\CifFile
  copying src\YappsStarParser_1_1.py -> build\lib.win-amd64-3.8\CifFile
  copying src\YappsStarParser_1_0.py -> build\lib.win-amd64-3.8\CifFile
  copying src\YappsStarParser_STAR2.py -> build\lib.win-amd64-3.8\CifFile
  copying src\YappsStarParser_2_0.py -> build\lib.win-amd64-3.8\CifFile
  copying src\StarFile.py -> build\lib.win-amd64-3.8\CifFile
  copying src\TypeContentsParser.py -> build\lib.win-amd64-3.8\CifFile
  copying src\parsetab.py -> build\lib.win-amd64-3.8\CifFile
  creating build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\drel_ast_yacc.py -> build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\drel_lex.py -> build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\drel_runtime.py -> build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\parsetab.py -> build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\py_from_ast.py -> build\lib.win-amd64-3.8\CifFile\drel
  copying src\drel\__init__.py -> build\lib.win-amd64-3.8\CifFile\drel
  running build_ext
  building 'CifFile.StarScan' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycifrw
  Running setup.py clean for pycifrw
Failed to build pycifrw
Installing collected packages: setuptools, patsy, imagecodecs, h5py, greenlet, fabio, wxutils, tomli, statsmodels, sqlalchemy, silx, pywin32, py, pluggy, iniconfig, attrs, atomicwrites, asteval, algopy, xraydb, wxmplot, termcolor, pytest, pyshortcuts, pyfai, pycifrw, psutil, peakutils, numdifftools, lmfit, hdf5plugin, xraylarch
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.2.0
    Uninstalling setuptools-61.2.0:
      Successfully uninstalled setuptools-61.2.0
    Running setup.py install for pycifrw ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\anaconda3\envs\xraylarch\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dongxiao FAN\AppData\Local\Temp\pip-record-5wux1uzc\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\anaconda3\envs\xraylarch\Include\pycifrw'
         cwd: C:\Users\Dongxiao FAN\AppData\Local\Temp\pip-install-40e_mgd2\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\
    Complete output (28 lines):
    running install
    D:\anaconda3\envs\xraylarch\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\CifFile
    copying src\__init__.py -> build\lib.win-amd64-3.8\CifFile
    copying src\CifFile_module.py -> build\lib.win-amd64-3.8\CifFile
    copying src\yapps3_compiled_rt.py -> build\lib.win-amd64-3.8\CifFile
    copying src\YappsStarParser_1_1.py -> build\lib.win-amd64-3.8\CifFile
    copying src\YappsStarParser_1_0.py -> build\lib.win-amd64-3.8\CifFile
    copying src\YappsStarParser_STAR2.py -> build\lib.win-amd64-3.8\CifFile
    copying src\YappsStarParser_2_0.py -> build\lib.win-amd64-3.8\CifFile
    copying src\StarFile.py -> build\lib.win-amd64-3.8\CifFile
    copying src\TypeContentsParser.py -> build\lib.win-amd64-3.8\CifFile
    copying src\parsetab.py -> build\lib.win-amd64-3.8\CifFile
    creating build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\drel_ast_yacc.py -> build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\drel_lex.py -> build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\drel_runtime.py -> build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\parsetab.py -> build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\py_from_ast.py -> build\lib.win-amd64-3.8\CifFile\drel
    copying src\drel\__init__.py -> build\lib.win-amd64-3.8\CifFile\drel
    running build_ext
    building 'CifFile.StarScan' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\anaconda3\envs\xraylarch\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dongxiao FAN\\AppData\\Local\\Temp\\pip-install-40e_mgd2\\pycifrw_ac1533fa99234bdd856a45b8bbc07d65\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Dongxiao FAN\AppData\Local\Temp\pip-record-5wux1uzc\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\anaconda3\envs\xraylarch\Include\pycifrw' Check the logs for full command output.

**Comment by newville** [comment]
@dxfan2022 What command did you run -- you give a lot of output but did not say what you did to get that output.

Pycifrw is one of the packages that we usually install from Anaconda.  It does not have binary wheels on PyPI for all platforms, so using `pip` would require a working compiler.

We should probably try to get rid of needing it entirely, but I'm not sure when that will happen.

**Comment by dxfan2022** [comment]
@newville Hi, Matt, 
The problem happens when I am installing Larch in the Anaconda base terminal. 
The command is: _pip install xraylarch_, which is the last step of installation of "[Installing into an existing Anaconda Python environment]".

I am wondering If I have succeeded in the installation. 
I met problem when I try to start programming according to Larch website tutorial (Chapter [8. Programming with Larch from Python](https://xraypy.github.io/xraylarch/python.html))

Like this:
 (base) C:\Users\username>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
--- import larch
 _**---from larch.xafs import autobk
            Traceback (most recent call last):
            File "<stdin>", line 1, in <module>
            ModuleNotFoundError: No module named 'larch.xafs'**_

I am very familiar with XAFS, and also know how to use XAS viewer in Larch GUI (already installed from the Binary installer).
But I am a beginner in Python. 
PS: Is there any introduction video tutorial for starting Larch programming as you have shown on Youtube for "[Larch for XAFS Analysis](https://www.youtube.com/watch?v=UKudem0nH_U&list=PLgNIl_xwV_vK4V6CmrsEsahNCAsjt8_Be)". I printed out your Larch website tutorial, and try to read (so long.....).

**Comment by newville** [comment]
@dxfan2022 OK, thanks.  
Yeah that looks like `pip install xraylarch` did not finish correctly.

(aside: installing from the binary installers does install a complete Python environment, ready to use.  You could also install a new Python environment for Larch with the GetLarch.bat or GetLarch.sh scripts - these are meant to give the same result as the binary installers.)

But, it looks like the documentation at https://xraypy.github.io/xraylarch/installation.html#installing-into-an-existing-anaconda-python-environment says to install some "core packages" from Anaconda.    In fact the list there is probably incomplete -- missing `pycifrw` in fact --  as the installers and GetLarch scripts actually do
 
`
    conda install -yc conda-forge wxpython tomopy scipy matplotlib scikit-image scikit-learn pymatgen pycifrw
`
 
which is probably what went wrong for you.  Probably just doing 

` 
conda install -y -c conda-forge pycifrw
`

will work correctly and then allow 

`
pip install xraylarch
`

to finish.   I guess we never tested doing that process by hand on Windows!

For documentation and videos: I apologize for these being all of ["incomplete", "way behind", and "way too long"] all at the same time!  

A video on scripting is a good suggestion - I am thinking about making a couple more videos, and maybe this topic could fit in with that.    Then again, I don't think it really makes sense for these to be teaching Python itself - there are lots of resources for that.

**Comment by dxfan2022** [comment]
Hi, Matt. Thank you very much. The installation is succeeded.
Looking forward to more videos on your Youtube channel.
