### ISSUE TITLE
PCA building model error

### ISSUE THREAD

**Issue by duoduoss** [xraypy/xraylarch#370]
Hello, 
I encounter an error when trying to use "build model with selected groups" in PCA (version 0.9.59): 

Traceback (most recent call last):
  File "C:\ProgramData\xraylarch2\lib\site-packages\larch\wxxas\pca_panel.py", line 338, in onBuildPCAModel
    opts = dict(groups=groups, arr=arrayname, xmin=form['xmin'], xmax=form['xmax'])
NameError: name 'arrayname' is not defined

Those same spectra can be used as components in LCF and the fitting works fine. 

Could you please help fix this? (Or I just wait for the new version ?)

Thank you very much!

**Comment by duoduoss** [comment]
I would like to mention this issue only happens for the Larch on my office PC. The Larch PCA works fine on my laptop. They are both 0.9.59.

**Comment by newville** [comment]
@duoduoss Sorry for this -- we've seen this too.  This is fixed in the master branch, and I'm hoping to release 0.9.60 later today or early tomorrow.
