### ISSUE TITLE
version 0.6.60 problem with "merge selected groups"

### ISSUE THREAD

**Issue by jo-schroe** [xraypy/xraylarch#371]
Hi Matt, I just started using the XASViewer from Larch and it worked great with the version 0.9.59. Today I did the update to version 0.6.60 and now unfortunately I cannot "merge selected groups" anymore. Thanks in advance.

**Comment by newville** [comment]
@jo-schroe Ack, and thanks.   I can confirm this... I'll have a fix in the development version tomorrow.  This might need a fixed release before the end of the week.

**Comment by jo-schroe** [comment]
Thanks Matt for taking care of it so fast!

**Comment by newville** [comment]
@jo-schroe I believe this is fixed in 0.9.61
