### ISSUE TITLE
[xas_viewer] how to resize a wx.Dialog window?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#372]
@newville some users have reported that on their machine cannot see all the buttons for some dialogs (e.g. the energy calibration one) and they cannot resize the window to get the buttons visible. I see that those are `wx.Dialog` objects instead of `wx.Frame`. Is there a way to have those windows resizable?

**Comment by maurov** [comment]
@newville a follow-up and related to this issue, today we gave a tutorial with Larch and the change of resolution of the projector made the buttons of the lower part of the windows not reachable. Is there a way in Wx to add a side slider when the main window is smaller than the inside widgets? Some widgets get a side slider when resized, other not.

**Comment by newville** [comment]
@maurov I think this should now be "much better" if not completely fixed.  The main XAS Viewer window can be compressed and scrolled.  Most of the "Results" windows can be scaled too...

**Comment by maurov** [comment]
@newville thanks for working on this. At first look it seems fine to me too.
