### ISSUE TITLE
Can't export data as .prj

### ISSUE THREAD

**Issue by LaurenPincus** [xraypy/xraylarch#373]
Hi @newville,

I'm having an issue with the latest version of Larch where I can't save my files as .prj. When I use the file save selected groups to athena project file, the dialog opens, I am able to type my file name, but no save file appears. Let me know if any other information would be helpful.

Thanks,
Lauren

**Comment by newville** [comment]
@LaurenPincus Oh, sorry.  I'll investigate that.

**Comment by newville** [comment]
@LaurenPincus sorry for the delay (and weekend), but I can't reproduce this -- exporting to Athena works for me.  So, yeah, maybe more info?

**Comment by maurov** [comment]
@LaurenPincus exporting to Athena works for me too. Please, could you provide a more detailed report of what is not working for you? Do you get any errors if you start xas_viewer from the shell? If not, please, close the issue.

**Comment by LaurenPincus** [comment]
Sorry for the delayed reply @maurov and @newville. I initially noticed the problem with very large data sets e.g. a few hundred scans, but I can't seem to reproduce it so I will close the issue. Thanks and sorry for the bother!
