### ISSUE TITLE
Larch not starting in a fresh conda environnement 

### ISSUE THREAD

**Issue by Crystal4276** [xraypy/xraylarch#376]
Hello,

I ran all all the command for conda installation in a newly created env (https://xraypy.github.io/xraylarch/installation.html#install-conda)

When starting larch i get those error messages:

(xraylarch) crystal@vmmint:~$ larch
Traceback (most recent call last):
  File "/home/crystal/miniconda3/envs/xraylarch/bin/larch", line 5, in <module>
    from larch.apps import run_larch
  File "/home/crystal/miniconda3/envs/xraylarch/lib/python3.9/site-packages/larch/__init__.py", line 54, in <module>
    from . import builtins
  File "/home/crystal/miniconda3/envs/xraylarch/lib/python3.9/site-packages/larch/builtins.py", line 46, in <module>
    from . import wxlib
  File "/home/crystal/miniconda3/envs/xraylarch/lib/python3.9/site-packages/larch/wxlib/__init__.py", line 42, in <module>
    from . import larchframe
  File "/home/crystal/miniconda3/envs/xraylarch/lib/python3.9/site-packages/larch/wxlib/larchframe.py", line 16, in <module>
    from wxutils import (MenuItem, Font, Button, Choice)
ModuleNotFoundError: No module named 'wxutils'

Those are the package installed in the xraylarch environnement:
https://pastebin.com/zt0nXdzv

Best,

**Comment by newville** [comment]
@Crystal4276 Sorry for the trouble, and thanks for the list of installed packages.  It looks like you need to do

```
pip install wxmplot wxutils 
```

and that we need to either fix that error or add that to the instructions.   

Basically, the idea is that we want to allow larch to work if wxPython is not installed.  So we do not want to be `wxutils` and `wmplot` to be "hard dependencies", as these can only be installed if wxPython is installed.  We do have lots of checks for "is wxPython installed", but then if it is, we are sort of assuming that these two packages are also installed.  I think documentation might be the easiest solution.

**Comment by Crystal4276** [comment]
Hello Matt,

Sorry, reading the solution, i realize now i could have figure this out myself.
I guess it was still useful to report it here...

Thanks, it's working fine.
i'll play around with the new version!

Best

**Comment by maurov** [comment]
@Crystal4276 thanks for reporting this.

@newville I saw you have forced to `python==3.9.12` in the documentation, is that a real need? I propose to keep `python==3.9` only. I propose to add in the documentation a warning to avoid installing with python 3.10 because in that case `wxpython` will result broken. Furthemore, since in the documentation we say to conda install wxpython, we should add to to pip install wxutils and wxmplot, without forcing wx-related dependencies in Larch.

**Comment by newville** [comment]
@maurov "3.9.12" is probably overly precise, but we sort of know that "works".  And 3.10 vs wxPython 4.1 has a few known issues (mostly related), and they have been slow to push a fix.    The biggest change is to remove the `conda update -all`.

But, yeah, we could probably change this...

**Comment by maurov** [comment]
@newville oh yes, we should definetively take out the `conda update -all`.

**Comment by Crystal4276** [comment]
The command conda update -all  in the documentation was probably to my former issue :
https://github.com/xraypy/xraylarch/issues/340
