### ISSUE TITLE
[xas_viewer/normalization] polynomial type does not stay persistent after group switch

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#379]
@newville here a bug report from a user on the beamline:

- open a file -> group 1
- select linear as polynomial type
- make a copy of group 1 -> group 2
- select group 2
- group 2: change the polynomial type from linear to cubic
- select group 1: the polynomial type is linear -> OK
- select group 2: the polynomial type is linear -> *WRONG* (should be cubic)

There is a workaround to make the parameters persistent, it consists of deselecting all groups and when selecting group 2, click on the Copy button (this make persistent the settings also for the current group).

No hurry to fix this

**Comment by newville** [comment]
@maurov I see similar weird things with the normalization "order" not being preserved correctly.  Will investigate.

**Comment by newville** [comment]
@maurov OK, I think this is now resolved in master, hoping to push out 0.9.63 soon...

**Comment by maurov** [comment]
@newville thanks for fixing this and all the nice work to get `0.9.63` out.
