### ISSUE TITLE
only wheel provided on PyPI?

### ISSUE THREAD

**Issue by reneeotten** [xraypy/xraylarch#380]
hi @newville - good to see you here as well! As you probably figured I have no immediate use myself for X-ray software, but the `xraylarch` package is packaged in MacPorts and the maintainer there (@joefowler) opened a [PR](https://github.com/macports/macports-ports/pull/15083) to update to the latest version. 

We typically install from the source distribution which doesn't work anymore now since as of v0.9.60 only the `.whl` file is present on PyPI. Of course we could install the `.whl` file but before we changing to doing so I just wanted to check whether it is intentionally that there is no `.tar.gz` file on PyPI anymore.  Thanks!

**Comment by newville** [comment]
@reneeotten It's mostly about size:  the wheel includes the code to be installed (20 Mb, as DLLs for all platforms, are included, and not separated by platform).  The tarball (maybe for historical purposes and going back to a time before things like github were common) includes all the documentation and examples - that's around 70 Mb.   "pip install" won't use all that stuff anyway, so wheels seem more efficient.

Would be helpful to push tarballs that did not include examples and docs?

**Comment by reneeotten** [comment]
thanks @newville for the response, I see your point on having "useless" files included in the distribution that are not used by `pip` anyway. We can probably just go ahead and use the `.whl` file for now and will get back to you if there is real benefit for us to get a tarball again. Alternatively, we could switch our sources to the GitHub repository - although sometimes the use of `setuptools_scm` causes trouble there and needs a full "checkout", which we also don't like ;)

**Comment by joefowler** [comment]
Thanks Matt @newville for your answer. @reneeotten helped me learn how to make a MacPort using the wheel file only, so I think we are all set. Discussion at [PR 15083](https://github.com/macports/macports-ports/pull/15083).

Please feel free, either of you, to close this issue. I believe it's fixed.
