### ISSUE TITLE
mback when pre-edge not already calculated

### ISSUE THREAD

**Issue by woutdenolf** [xraypy/xraylarch#382]
I believe this is a bug:

https://github.com/xraypy/xraylarch/blob/1387e3d3d5487bde96de99b54f1e20e5361eddf5/larch/xafs/mback.py#L275-L279

I assume this needs to call `pre_edge(..., group=group)` and not `preedge(...)`, otherwise how is `group` supposed to get the `pre_edge` attribute?

**Comment by woutdenolf** [comment]
Here is a minimal example:

```python
import numpy
from larch.symboltable import Group
from larch.xafs.mback import mback_norm

filename = "./examples/xafs/cu_rt01.xmu"
data = numpy.loadtxt(filename)
energy, mu, norm = data.T

spectrum = Group(energy=energy, mu=mu, norm=norm)

opts = {
    "z": 29,
    "e0": 8980.5,
    "pre1": -190.0,
    "pre2": -65.0,
    "norm1": 150,
    "norm2": 1165.0,
    "nnorm": 2,
    "nvict": 0,
}
mback_norm(spectrum, group=spectrum, **opts)
```

**Comment by newville** [comment]
OK, I think this is resolved (in the master branch) - your example works for me now.  Thanks!
