### ISSUE TITLE
[xas_viewer] add "New fresh Larch Session" action

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#387]
@newville I got a "vague" report from a user about the fact that the `.larix` session file hugely increasing in size after linear combinations fits (from Mb to Gb size). Furthermore, in order to avoid restarting xas_viewer on slow virtual machines (see #378), it would be beneficial to have the possibility to start a "fresh" Larch session (cleaning everything loaded so far) from the File menu. This is equivalent to Quit and restart xas_viewer. What do you think?

**Comment by newville** [comment]
@maurov 

>I got a "vague" report from a user about the fact that the .larix session file hugely increasing in size after linear combinations fits (from Mb to Gb size)

I've seen projects grow to 100's of Mb.  For sure the idea of saving all combinations for linear combinations leads to a lot of unneeded results -- such as having one "combination" with 5 components and then several combinations with 6 components, but one of the components with weight < 1.e-5 -- essentially zero. 

I will look into a) adding a "component weight threshold" (say, default 1.e-3) -- if any combination as a component with a weight below that, it won't be saved (idea may need some fiddling, say checking that a combination with the remaining components *is* saved).


> Furthermore, in order to avoid restarting xas_viewer on slow virtual machines (see https://github.com/xraypy/xraylarch/issues/378), it would be beneficial to have the possibility to start a "fresh" Larch session (cleaning everything loaded so far) from the File menu. This is equivalent to Quit and restart xas_viewer. What do you think?
 

Yes, I did add a "clear_session" command in the code -- the GUI could easily expose this and should.  I often just "select all groups" and then remove them all.  That doesn't clear everything, but "most stuff".  But, yes, I will add that.

**Comment by newville** [comment]
@maurov Two things:
 
a) Results of linear combination fittings are now checked for "unique non-zero components", and then further limited to the top N results (as measured by reduced chi-square, with N=16).  That will avoid a lot of "effectively duplicates" (for example,  A =0.3, B=0.7, C=1.e-10 and A=0.3, B=0.7, D=1.e-10).  In my test examples, this really means that the top ~10 results will really get down to the "not very good" level.

b) there is now a "clear session" menu option that will give an "Are You Sure?" prompt, then autosave the current session,  and finally remove all the data saved in the session.

**Comment by maurov** [comment]
@newville thanks for adding these features.
