### ISSUE TITLE
[xas_viewer/normalization] Y offset not working

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#389]
@newville in xas_viewer normalization panel changing the 'Y offset' has no effect. Here what I do to reproduce this:

- import data
- select >2 groups
- put a value in 'Y offset'
- click on 'Plot selected groups' -> the plot does not take into account the 'Y offset' value

**Comment by newville** [comment]
@maurov thanks, this is now fixed with e01260062dc84b6ebb7dccb87cb735cdb361b359

**Comment by maurov** [comment]
@newville thanks for fixing it
