### ISSUE TITLE
installation joke?

### ISSUE THREAD

**Issue by erdzeichen** [xraypy/xraylarch#390]
Hej,
your provide a very careful installation instructions. For windows 10 the script (and the binary installation) fails and says wrong compiled version. When following your installation instructions I get:

Traceback (most recent call last):
  File "C:\Users\Jens\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jens\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jens\anaconda3\Scripts\larch.exe\__main__.py", line 4, in <module>
  File "C:\Users\Jens\anaconda3\lib\site-packages\larch\__init__.py", line 1, in <module>
    raise ImportError("larch cannot be installed with pip, try installing using conda-forge instead.\nSee https://larch.newman.me/getting-started.html for instructions.")
ImportError: larch cannot be installed with pip, try installing using conda-forge instead.
See https://larch.newman.me/getting-started.html for instructions.

but you suggest to do exactly this.

**Comment by erdzeichen** [comment]
Hej I suggest to replace the second but last line in:
conda create -y --name xraylarch python=>3.9.10
conda activate xraylarch
conda install -y "numpy=>1.20" "scipy=>1.6" "matplotlib=>3.0" scikit-learn pandas
conda install -y -c conda-forge wxpython pymatgen tomopy pycifrw
pip install xraylarch
larch -m

with
conda install xraylarch -c conda-forge

**Comment by newville** [comment]
@erdzeichen Sorry for the trouble, but no, the installation instructions do not contain any jokes.

We do not currently support a conda package for xraylarch and do indeed recommend installing xraylarch with pip.   There may be some xraylarch conda packages, but they are likely to be out-of-date.  

It sort of looks to me like some other package named "larch" has been installed.  I don't recognize the 
```
       File "C:\Users\Jens\anaconda3\Scripts\larch.exe_main.py", line 4 
```
or 
```
File "C:\Users\Jens\anaconda3\lib\site-packages\larch_init.py", line 1, in
```

and have no idea how those got installed with the GetLarch script.   

But, I also did not see from your message where in the installation process this error message came from.  Do you have any further information on where in the process this happened?

**Comment by erdzeichen** [comment]
Hey matt,
I installed the package using pip, but when I import it or when I run "larch -m" I get this error message. 
Btw I also think that pipy is the better option.
Best
Jens

**Comment by newville** [comment]
@erdzeichen Oh, OK, I can see that there is some other program/script called `larch` installed,  that `larch -m` could cause problems.

If there is some other *library* called larch installed, I am not sure how to resolve that.   If you are up for trying some python, 
you could try:

```
C:~> python
>>> import larch
>>> print(larch.__file__)

>>> from larch.apps import make_desktop_shortcuts
>>> make_desktop_shortcuts()
```

If there is a different `larch` library that you need to use, I think we have to figure out how to avoid that namespace collision.

Do you know how that got installed or what it does?

**Comment by erdzeichen** [comment]
Mmmh now I feel a little bit stupid. I did not realise the namespace crash. After uninstalling both, manually deleting the larch folder and then re-installing xraylarch the scripts work as intended. 
Thank you  Matt, also for many great scripts!
Best Jens

**Comment by newville** [comment]
@erdzeichen OK, thanks, no worries, and glad you got it worked out.  In fact, I verified a fresh install on Windows in the meantime and it worked

But, I still would like to figure out how to detect and avoid such a name clash: I don't know that you will be the only one to see that -- and I suspect many users will be more stuck on such an issue than you were!

**Comment by erdzeichen** [comment]
Well one way would be to charge the import and call to xraylarch instead of larch.
 I'm running on three different computers, so most likely I installed larch at one time manually myself. But let me know if I should test something. 

Btw, could you add in the deglitch window the option to plot chi(k) with the amplifications chi*k and chi*k^2 instead of only chi(E). ( I know that there is a pseudo k x-scale, but this is not the same) 
Also if there would be an option to plot only a fraction of the data space, that would be helpful. Data from MaxIV has sooo many glitches that I spend a lot of time in this window... 

I'm looking of implementing now xraylarch into kimopack for time evolution analysis. 
Best Jens
