### ISSUE TITLE
module 'larch' has no attribute 'io' -  public release 0.9.65

### ISSUE THREAD

**Issue by ahoffm02** [xraypy/xraylarch#392]
Hi All,

I just upgraded from larch 0.9.50 to 0.9.65.

I just tried to run my code with a few new tweaks and it has hung on my read data step that reads the ascii data using larch.io.read_ascii() and it failed.

Error message: module 'larch' has no attribute 'io' 

Image for posterity.

![image](https://user-images.githubusercontent.com/65635006/178126690-5ba87b3a-d030-4319-8413-d370edbad520.png)

Can you let me know what happened to larch.io?

**Comment by maurov** [comment]
@ahoffm02 sorry for the trouble. We are trying avoiding loading too many modules in the `larch` workspace to optimize speed (as discussed in #378).

I recommend to simply use `from larch.io import read_ascii` in your code to fix this error.

**Comment by ahoffm02** [comment]
Thanks!

This suggestion worked.

Cheers!
