### ISSUE TITLE
[larch/xafs/fefffit.py] Initialization of 'delta_chi'

### ISSUE THREAD

**Issue by Nothinel** [xraypy/xraylarch#400]
Hello,
In line 254 of "larch/xafs/feffit.py" delta_chi is initialized with a default value of "1.0" by
`self.data.delta_chi = getattr(data, 'delta_chi', 1.0)`
Hence, if no `delta_chi` is given and the feffit() function ist called with the according data, the following error occurs:
>Traceback (most recent calls last): 
>    out = feffit(pars, dset)
>      ^^^
>   File fit.lar, line 53
>  File "/home/admin/xraylarch/lib/python3.9/site-packages/larch/closure.py", line 76, in __call__
>    return self.func(*args, **kwds)
>  File "/home/admin/xraylarch/lib/python3.9/site-packages/larch/xafs/feffit.py", line 566, in feffit
>    ds.prepare_fit(params=params)
>  File "/home/admin/xraylarch/lib/python3.9/site-packages/larch/xafs/feffit.py", line 313, in prepare_fit
>    _dchi = interp(self.model.k, self.data.k, self.data.delta_chi)
>  File "<__array_function__ internals>", line 180, in interp
>  File "/home/admin/xraylarch/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1570, in interp
>    return interp_func(x, xp, fp, left, right)
>
>ValueError: object of too small depth for desired array

I believe this is caused because `self.data.delta_chi` is given as `fp`to `numpy.interp_func`, which is expected to be an array (and not a single float). 

In my cases, where delta_chi seems to either not exist or not to be imported see #399, I could hotfix the problem by commenting out the above mentioned line 254 and hence not initializing `delta_chi` at all. 

If any additional information is required I will be happy to supply what I can.

**Comment by newville** [comment]
@Nothinel thanks, and good catch.  I think all the cases / testing I've done, chi(k) comes from a `autobk()` which generates a `delta_chi` array.  

Will fix.
