### ISSUE TITLE
XAS Viewer cannot handle opening non-UTF8 files

### ISSUE THREAD

**Issue by kaarelmand** [xraypy/xraylarch#406]
XAS Viewer is a great piece of software, but I did run into a bit of a hiccup. Currently, when XAS Viewer reads a text file containing column data, it assumes that the data is encoded in UTF-8. Sadly, this is not always the case. At the LUCIA beamline in SOLEIL, for example, their Igor software exported all data in Western (ISO-8859-15) encoding. Loading this in XAS Viewer results in a `UnicodeDecodeError` (see full traceback below). Re-saving the files in UTF-8 makes them work perfectly.

Should you decide that non-UTF-8 is something worth supporting, I can see either using an automatic detector like `charset-normalizer`, or just allowing the user to indicate the alternative encoding upon `UnicodeDecodeError`.

```
Traceback (most recent call last):
  File "/home/user/Develop/xraylarch/larch/wxxas/xasgui.py", line 1152, in onReadDialog
    self.onRead(path)
  File "/home/user/Develop/xraylarch/larch/wxxas/xasgui.py", line 1177, in onRead
    self.show_subframe('readfile', ColumnDataFileFrame,
  File "/home/user/Develop/xraylarch/larch/wxxas/xasgui.py", line 1105, in show_subframe
    self.subframes[name] = frameclass(self, **opts)
  File "/home/user/Develop/xraylarch/larch/wxlib/columnframe.py", line 336, in __init__
    group = self.initgroup = self.read_column_file(self.path)
  File "/home/user/Develop/xraylarch/larch/wxlib/columnframe.py", line 628, in read_column_file
    reader, text = guess_filereader(path, return_text=True)
  File "/home/user/Develop/xraylarch/larch/io/columnfile.py", line 607, in guess_filereader
    text = fh.read().decode('utf-8').replace('\r\n', '\n').replace('\r', '\n')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 141: invalid start byte
```

**Comment by newville** [comment]
@kaarelmand Sorry for the trouble. Can you send an example file?  Somehow, I thought that Latin-1 was a subset of UTF-8 (ie, they agreed on the first 255 characters), but maybe that is not correct.  I'm not sure about IOS-8859-15. 

If it's not "UTF-8" or "Latin-1", I'm not sure how to try to guess the encoding of a file.  We found that relying on "system encoding" was definitely not very reliable -- as files move between computers, the current default encoding might not be the right one to read data from some far-away beamline.  But, suggestions welcome.

**Comment by kaarelmand** [comment]
No trouble at all; this is easy to sidestep. Just thought it might be useful for me to open issues for the hiccups I've encountered.

Here is the file in question: [ALARA_JV07_map1_POI1_1.zip](https://github.com/xraypy/xraylarch/files/9622822/ALARA_JV07_map1_POI1_1.zip)

As for how to solve it; one option are various python libraries for guessing encoding: [chardet](https://github.com/chardet/chardet) and [charset_normalizer](https://github.com/Ousret/charset_normalizer). However, I'm not sure this is something you want to add another dependency for. Perhaps it would be more straightforward to simply ask the user what the encoding is, if unicode doesn't work. I thought I might try to write a PR for this later, though I'm very new to all this.

**Comment by newville** [comment]
@kaarelmand Thanks -- I'll add that datafile (truncated) to the tests, it that is OK with you.  

Using `chardet` is a fine idea -- I'll do that.

**Comment by kaarelmand** [comment]
With the latest commits, my files seem to open perfectly. Thanks!
![image](https://user-images.githubusercontent.com/16322491/192315904-776f39c6-aeb5-437f-93ed-88e3aed4b292.png)
