### ISSUE TITLE
plotting individual path after fitting 

### ISSUE THREAD

**Issue by duoduoss** [xraypy/xraylarch#417]
Dear @newville : 

I was trying to plot each individual path after EXAFS fitting using Spyder. The "plot_paths_k" and "plot_plaths_r" commands didn't work with error message "'FeffitDataSet' object has no attribute 'pathlist'".  In the script, I  have a "pathlist" or "paths": 

"dataset= feffit_dataset(data=thisgroup, pathlist=[ path1, path2, path3], transform = trans)" 

The function "plot_chifit(dataset)" works well. If I use "plot_chir" or "plot_chik" to plot the "dataset.paths['path name']", i got the calculated one but not the fitted. 

I am wondering how I can fix this, and also whether it is possible to export the fitted chik and chir of individual path for plotting. 

Thanks you very much

**Comment by newville** [comment]
@duoduoss If you are asking for help with something you did that is not working as you expect, you sort of have to explain what it is that you actually did that is not working as expected.  You did not post any such code.  You set up a dataset.  Apparently you did a fit.  And.... I don't know.... something else? 

There are lots of examples and fitting with XAS Viewer actually generates a fitting script. 

Post actual code of what you did.
