### ISSUE TITLE
No 'whiteline' argument in mback

### ISSUE THREAD

**Issue by rachelelim** [xraypy/xraylarch#423]
According to the documentation 13.2.4, mback should have a kwarg 'whiteline' that excludes a region around the white line when doing the fitting. I looked at mback.py file under xafs, and it looks like that argument doesn't exist

**Comment by newville** [comment]
@rachelelim. Oh, thanks! I don't recall what changed, but I'll look into that...

**Comment by gnzng** [comment]
Just had a quick look via blame, whiteline was replaced/deleted by commit [https://github.com/xraypy/xraylarch/commit/f6d01f22855090f6e722e40848c7c80a1a27902e](https://github.com/xraypy/xraylarch/commit/f6d01f22855090f6e722e40848c7c80a1a27902e)

**Comment by newville** [comment]
@gnzng Thanks Damian, yeah I sort of think the `whiteline` option never really worked well (or maybe "in a way that I understood").   I was trying to figure that out again, but I think @rachelelim's proposed change to the documentation might be the most sensible thing to do: match the actual behavior.

But if either of you has a strong opinion on how to improve this (or maybe some other idea for working better in the presence of a strong white line), I'd be happy to do so.  Thanks!
