### ISSUE TITLE
coordinate release 0.9.69

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#438]
@newville we will have our [ASTER'X 2023 school](http://f-crg.fr/ecole-thematique-cnrs-asterx-2023/) soon and I would like to have a next release of Larch (v0.9.69) by next week, let's say aroun **June 7th 2023**, including the following issues:

- [x] #311 
- [x] #434 
- [x] #414 

Does this sounds feasible for you?

**Comment by newville** [comment]
@maurov Yes, it is time for a new release!  I guess I would ask what needs immediate attention before a release.

For #414, I think this is OK but I'm not sure everyone agrees, so there may still be trouble?  
For #311, I think the current version sort of works, but probably needs real-world testing and suggestions, and is not really even started for multi-column Spec files.

For the school on June 7, should we aim for Friday (June 2) or Monday (June 5)?

**Comment by maurov** [comment]
@newville thanks for agreeing in having next release soon.

> @maurov Yes, it is time for a new release! I guess I would ask what needs immediate attention before a release.

Yes, we may ask in the Slack developers' group too.
 
> For #414, I think this is OK but I'm not sure everyone agrees, so there may still be trouble?

I will check these days and let you know my point of view by commenting in the issue thread.

> For #311, I think the current version sort of works, but probably needs real-world testing and suggestions, and is not really even started for multi-column Spec files.

Idem, I will give my feedback as soon as possible.

> For the school on June 7, should we aim for Friday (June 2) or Monday (June 5)?

The school starts on Monday June 12, so having a release by Friday June 9 (at latest) is the best for me. This will give us some more time to cross check if there are urgent bugs to fix.

**Comment by newville** [comment]
@maurov sounds good. 
How about this: I willl push 0.9.69rc1 to pypi on June 5th, but I won't push automatic updates.  On June 9th, I will plan to push 0.9.69 and make that an announced release.

**Comment by newville** [comment]
@maurov I tagged and pushed 0.9.69 to PyPI and here as a "pre-release".  I'll send out a more complete description in the morning.  Let's aim for 0.9.70 for Friday.

**Comment by newville** [comment]
@maurov I think we did all of this!
