### ISSUE TITLE
conda-forge recipe for xraylarch

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#439]
@newville I would like to maintain a conda-forge recipe for `xraylarch` (from PyPI via grayskull). I am ready to make a pull request (to conda-forge):

https://github.com/maurov/staged-recipes/blob/xraylarch/recipes/xraylarch/meta.yaml

For those who want to use Larch with Wx (and Jupyter), this would be as simple as `conda/mamba install -c conda-forge xraylarch`. This way we do not need to hard code single conda/mamba packages in `.github/workflows` and in the install scripts.

Do you have anything against it?

**Comment by newville** [comment]
@maurov it's OK with me to try to do this.  I gave up maintaining conda packages, though I do sort of help out with existing conda-forge recipes for some packages, but those are relatively easy.  I would suggest going through a few development cycles with it before committing to the idea.

Personally, I would much rather support `pip install xraylarch`.  

It is fine with me to experiment with github workflows.

**Comment by maurov** [comment]
@newville thanks for being open to this. I will give it a try and will see how it goes. For now, nothing will change in the Larch distribution.

**Comment by newville** [comment]
@mrakitin Thanks -- I guess I thought that discussion was about what to include as dependencies in a conda recipe in general and the NSLS-II feedstock.  I guess that I forgot that you proposed a `conda-forge` feedstock.   But, to be clear, it is perfectly fine with me that you (and/or other people) want to maintain such conda packages on any repos.  Or other (deb, MacPorts, etc) packages.

The point I was trying (probably poorly!) to make is that while conda-forge sort of claims to be a de-facto standard repository of Python and Python-related (and maybe other scientific computing) packages, from the "conda" point-of-view it is just another "channel", and conda-forge does not do anything specifically to contact, involve, or review who has been developing or maintaining feedstocks.  It's really sort of a complaint about conda-forge and their own claim to

**Comment by mrakitin** [comment]
The feedstock https://github.com/conda-forge/xraylarch-feedstock/ already exists. I've invited @maurov to the maintainers' team.

**Comment by maurov** [comment]
@mrakitin thanks for adding me to the maintainers' team. I was not aware of an existing conda-forge package for Larch, this is why I initiated one from scratch. I will check the current recipe and propose a pull request soon. I would like to get uniform conda requirements between the Larch install scripts, github workflows and the conda-forge recipe. Is that fine with you?

@newville should we update the documentation to clearly state the possibility to install larch from conda forge?

**Comment by newville** [comment]
@maurov I'm OK with adding this to the docs.  I am OK with **adding** a test using this.  I am less OK with removing tests that use `pip install`.   

I am going to continue to insist that `pip install` is the preferred installation method, and that no other package manager (conda, deb, yum, MacPorts, homebrew, ....) is required.  If some people want to use any of those existing environments, that is fine.  Supporting `pip install` ought to make it clear what the dependencies are for those other package managers.   We don't endorse or give special treatment to `conda` or `conda-forge`.   When we distribute installers, we might use one of those -- we currently do use anaconda-based tools and environments.  We don't have immediate plans to change that, but we are not committed to those tools.  They are a means to reach the goal of making easy-to-use installers.

**Comment by maurov** [comment]
@mrakitin I have been trying installing larch via conda-forge lately on various Linux (or Windows WSL) machines and unfortunately it never worked for me! Does it really work for you?

**Comment by maurov** [comment]
I put some news here. With the help of @t20100 we are advancing in packaging a working `xraylarch` package on conda-forge.

Related:

- https://github.com/conda-forge/wxmplot-feedstock/pull/16
- https://github.com/conda-forge/wxutils-feedstock/pull/5

@newville, we will make two packages: `xraylarch-base` (to use Larch as a library) and full one `xraylarch` with all dependencies in in
