### ISSUE TITLE
Is flattening wise?

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#44]
Is flattening (in the style of Athena) a wise form of data processing or would the user be better served by doing something like Ifeffit's Cromer-Liberman normalization or Tsu-Chien Weng's MBACK.  Athena's flattening is a fully empirical way of approximating CL or MBACK normalization, but should it be done?

Of course, the flattened spectrum is not used to extract chi(k) in Athena, so it causes no harm in that sense.  But flattened spectra can be used for LCF, PCA, peak fitting, etc.

**Comment by maurov** [comment]
I think we can close this **old** issue. The user can visualize both in xas_viewer. If something still need to be discussed, just reopen the issue.
