### ISSUE TITLE
A bug report in XAS viewer (ver. 0.9.70)

### ISSUE THREAD

**Issue by otden** [xraypy/xraylarch#446]
I report a bug in version 0.9.70.

In version 0.9.68, "Rebin Data" worked when QXAFS data measured with PF was loaded, and the" OK button" was pressed, but not in version 0.9.70. 
My system is Windows 11.

Please validate and fix the bug, as the data is attached.
[ag05_0_Ag_foil.txt](https://github.com/xraypy/xraylarch/files/11830869/ag05_0_Ag_foil.txt)

Best,
Ot Den

**Comment by newville** [comment]
@otden Thanks for the report and sorry for that problem.   Basically, 0.9.70 was failing to read the mono d spacing.   This is now fixed in the master branch. 

You should be able to do install the latest version with this fix  with

```
python -m pip install https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl
```

**Comment by maurov** [comment]
@newville thanks for fixing this (https://github.com/xraypy/xraylarch/commit/d60df6883e158f86f033e7e2ad7ae8a5040535d5)!

@otden I am closing the issue. If it does not work for you, please, simply reopen it.

**Comment by otden** [comment]
Thank you very much for fixing the bug quickly !
