### ISSUE TITLE
Export Data (pre-edge peak)

### ISSUE THREAD

**Issue by mrvejar** [xraypy/xraylarch#452]
Export Data file function appears to not be working properly (does not open window to create data file on windows explorer, using windows 11). This appears to be specific to a plot that includes both the baseline-subtracted and the residual plotted in the same graph. Other graphs in pre-edge peak do not appear to have this issue so far.

**Comment by newville** [comment]
@mrvejar Do you mean "export data" from the plot window or do you mean from someplace else from XAS Viewer?

**Comment by mrvejar** [comment]
Yes, from the plot window only

**Comment by newville** [comment]
@mrvejar OK, thanks.  I'll look into that.

**Comment by newville** [comment]
@mrvejar This should be fixed in xraylarch 0.9.71 and wxmplot 0.9.56

**Comment by mrvejar** [comment]
@newville  Thank you so much! I have closed this issue.
