### ISSUE TITLE
Standard error is not calculated correctly if non used parameter is added

### ISSUE THREAD

**Issue by Ameyanagi** [xraypy/xraylarch#473]
@newville 

The standard error is not calculated correctly if the non-used parameter is added to the fit.

model:
<img width="712" alt="image" src="https://github.com/xraypy/xraylarch/assets/77273474/87668c12-c9e5-4f2e-8cfb-a9e0f8e713a9">

Correct fit with parameters matching with the model:
<img width="1022" alt="image" src="https://github.com/xraypy/xraylarch/assets/77273474/3e467bfd-e6c9-4672-95ca-da4c33f3a3f1">

Standard error not correctly calculated when a none used parameter is added: 
<img width="1015" alt="image" src="https://github.com/xraypy/xraylarch/assets/77273474/ac2ee13f-f977-4dea-b30e-ffcd02ae11c9">

**Comment by newville** [comment]
@Ameyanagi I believe this is now fixed in the master branch.

**Comment by Ameyanagi** [comment]
@newville 

I was trying to check the modification (from the master branch), but I couldn't do it because there were some issues in the feffit panel.
Were there any changes that prevents auto inclusion of the parameters to the Parameter window?

If I remember correctly, when we include the path to the feff fitting window, the parameters were automatically loaded to the parameters tab.
However, this is not happening now, and I couldn't change the setting of the parameters from the parameters tab.

I can look into detail, but I just wanted to know if you also have the same issue that can be resolved easily.

The instruction to reproduce:
1. load foil
2. calculate EXAFS
3. Run calculation from "Browse CIF Structure, Run Feff"
4. import first path

The parameters not loaded after importing the first path in the feff calculation:
<img width="766" alt="image" src="https://github.com/xraypy/xraylarch/assets/77273474/ba6b5910-8fe8-496c-a14d-0085559dda2e">

**Comment by newville** [comment]
Hm, that should work... I will try to look at it.

**Comment by Ameyanagi** [comment]
I will try recreating the environment.

**Comment by newville** [comment]
@Ameyanagi sorry for the trouble, silly mistake, and I think this is fixed now!

**Comment by Ameyanagi** [comment]
@newville 

I confirmed that it is fixed in the master branch.
Thank you very much!!

**Comment by newville** [comment]
OK, fixed in 0.9.73
