### ISSUE TITLE
Rbkg resetting to 1.00

### ISSUE THREAD

**Issue by SiebevanderVeer** [xraypy/xraylarch#476]
Hi,

In the current version of Larix (0.9.72) I'm doing some data fitting and came to the conclusion that I might want to experiment with tuning Rbkg some more. I made copies of the original group and changed Rbkg, but everytime I view a different group the Rbkg value resets to 1. It does this also for the original group. Any other parameter I change is saved when moving back and forward between groups, but not for Rbkg. The only place the change gets stored is in the Rmin for the Back Fourier transform.

Not sure if this is relevant to share, but the group I'm working in is a group that is a merge of a number of spectra and is a Larch session that I have saved and loaded quite often by now. Everything else seems to be working fine.

Best,

Siebe

**Comment by newville** [comment]
@SiebevanderVeer  Sorry for that and thanks for the clear report of behavior.   I'll investigate.

**Comment by SiebevanderVeer** [comment]
Much appreciated!

**Comment by newville** [comment]
@SiebevanderVeer Very sorry for the delay.  I believe this is now fixed in the development version.  If you are impatient and/or brave, you should be able to install a fix following the instructions at:

https://xraypy.github.io/xraylarch/installation.html#installing-the-development-version

**Comment by SiebevanderVeer** [comment]
Haha, thanks a lot!

**Comment by newville** [comment]
OK, this is now fixe in 0.9.73!
