### ISSUE TITLE
Modelled data shift

### ISSUE THREAD

**Issue by SiebevanderVeer** [xraypy/xraylarch#478]
Hi all,

I see something odd while data fitting. After I do fit I get a plot where the model follows the data (work in progress of course), but as soon as I change the view of the data, e.g. turn off plotting each path, the modelled data shifts. See images below as an example. 

I'm not 100% sure which of the two is the actual fitted model that larix provides the fit statistics and parameter values for.

Best,

Siebe 

![After fit](https://github.com/xraypy/xraylarch/assets/126678331/a38d66a6-12c4-48fe-b343-583c19375802)
![After deselecting plot each path](https://github.com/xraypy/xraylarch/assets/126678331/f3ac308b-4a7c-4f98-aad7-5490bd7cf0b1)

**Comment by newville** [comment]
@SiebevanderVeer Hm, not sure... that does look strange.  Can you post or send by email a Session File with this?

**Comment by newville** [comment]
@SiebevanderVeer Thanks for the project file -- I can reproduce these plots.  It looks to me like things are mostly OK, and I'm wondering if maybe it just some confusion.  

From the Fit results window, I get basically the same as what you get:

Fit Result "Plot Current Model"  with "Plot Each Path"  unchecked:

![image](https://github.com/xraypy/xraylarch/assets/304251/98886904-a254-4556-b7c1-edf356b39227)


Fit Result "Plot Current Model" with "Plot Each Path" checked:

![image](https://github.com/xraypy/xraylarch/assets/304251/3ad774f2-241c-4ce5-bf7d-2feb9dd6651e)

Those seem consistent to me, and what you see for "fit, with all the paths".

But then, if I go back to the Feffit Window and click "Plot Current Model" from there, I get

![image](https://github.com/xraypy/xraylarch/assets/304251/da054ec6-8cd0-4000-81c8-b4fb37db707e)

which looks a lot like your second plot.   But this plot from the Feffit window that plot is with the model *before* fitting, without the refined parameters -- basically "Initial fit".    Does that make sense and seem like maybe what is going on?  Or are you getting your second plot from the "Feffit Results" window?  

For me (with the latest version??), all of your fits labeled "Nov-17 ..." in the Feffit Results page show the peak amplitude of the model is slightly below the peak amplitude of the data, as in your plot with all the paths.

It should be that from the "Feffit Results" window, you can click on "Update Model with these values" to make the refined values the new initial values in the main Feffit Window.  But that is not done by default for each fit.

**Comment by SiebevanderVeer** [comment]
Ah, I see. You are correct, that is what I'm doing. I did not connect the
dots that the main window uses those values for the plot.

Thanks a lot for clarifying this for me.
