### ISSUE TITLE
plot_chiq does not work in Jupyter

### ISSUE THREAD

**Issue by Cathyhjj** [xraypy/xraylarch#488]
@shellydkelly and I are testing the latest Github version of Larch in Jupyter Notebooks. We noticed a potential syntax error in `plot_chiq()`. It returned an error that 
> 'kmin' is not defined. 

We tried to fix it locally by adding `kmax=None` as one of the default kwargs in the plot_chiq() function.

**Comment by newville** [comment]
@Cathyhjj OK, I'll look into that. Is that using the "plotly" version "plot_chiq" function?  If not, can you give a brief example?

**Comment by Cathyhjj** [comment]
Yes, it's using plotly: 

`from larch.plot.plotly_xafsplots import plot_chiq`

`plot_chiq(dgroup)`

I just realized that I had a small typo before. `kmin=None` needs to be added as a default kwarg in the plot_chiq() function for this function to work.

**Comment by newville** [comment]
@Cathyhjj  Thanks, yes that will fix it.  I added a similar fix to the development version of the code too.

**Comment by Cathyhjj** [comment]
Thank you! I'll close this issue.
