### ISSUE TITLE
multiple datasets fitting using feffit

### ISSUE THREAD

**Issue by Cathyhjj** [xraypy/xraylarch#497]
I noticed that when fitting multiple datasets using feffit in Jupyter notebook, for example 
`result = feffit(pars_all, [dset1, dset2, dset3])`, it only varies params for the last dataset, i.e., dset3, even though I set `vary=True` for corresponding paths' params used by dset 1 & dset2. 

It looks like `result = feffit(pars_all, [dset1, dset2, dset3], fix_unused_variables=False)` may help fix this issue and fit all the parameters? But this may be a little bit confusing to me..

**Comment by newville** [comment]
@Cathyhjj I think this might be working better in the sorry-not-yet-released version (I'm on work travel, and also trying to get many of the requests from you, Shelly, and George ;) ).    

Can you try installing the development version with 
   python -m pip install https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl

and trying that?

**Comment by Cathyhjj** [comment]
The new dev version (https://millenia.cars.aps.anl.gov/xraylarch/downloads/xraylarch-latest-py3-none-any.whl) solves the issue! Thank you! 

I just realized that you actually have feffit.py fixed and updated on Github last month.. My bad :), next time will try to upgrade my version first before opening a ticket
