### ISSUE TITLE
Atoms plugin in Larch?

### ISSUE THREAD

**Issue by maurov** [xraypy/xraylarch#51]
Does anybody is planning to port "atoms" to Larch? If not, I could probably invest some time in this. I never went through the source code of atoms itself, so the ideas I have in mind on how to implement it could result not compatible with Demeter then...

The Larch plugin I have in mind should simply do: 1) read a CIF file and some keyword parameters; 2) based on this, it will return a FEFF\* or FDMNES input file.

For the templates, I think is enough the 'string.Template' included in the Python standard library (there are tons of powerful template systems available, but this will avoid to include a further dependence in Larch).

For the CIF parsing, well, I think we are obliged to include a dependence on an external library. Do you have any preference for this? I'm evaluating some of them and at the moment the one I like the most is in ASE (https://wiki.fysik.dtu.dk/ase/index.html)... well, this is using a sledgehammer to crack a nut.

Anyway, your feedback is welcome.

**Comment by maurov** [comment]
@newville I think this is exactly what `cif2feff` does, closing then!

**Comment by newville** [comment]
@maurov yeah, it took a long time and it ended up using pymatgen as you suggested years ago - I did end up borrowing from but sort of rewriting the pymatgen 'convert CIF structure to feff input'.  It can write feff8 or feff6 input, and tries to handle fractional occupancy by weighted random selection. 

Mostly, though, I wanted to replace the need for webatoms and include a collection of CIF files. There is now an Sqlite3 database "larch/xrd/amscif_trim.db" (~10Mb) that has ~9K CIF structures from the American Mineralogical collection.  If the user is connected to the internet and can access https://millenia.cars.aps.anl.gov, there is a "full" version of this collection, with ~20K structures files (~30Mb) that will be downloaded (or try to, falling back to the "trimmed" version. 
FWIW, the "trimming" removes some obvious repeats, as from P- or T-dependent structures in a single publication and structures with more than 12 atoms/sites. 

Whichever version is used, this collection can be searched with a "cif browser" GUI form (available from XAS Viewer's Feff menu).   With that, CIF files can be searched and selected and can be converted to Feff input files (which can also be edited in place, of course), and then Feff8 or Feff6 run, with runs in separate folders under $HOME/.larch/feff/.    The CIFs can also display a 1D XRD pattern, though I don't know how useful that would be.  I believe there isn't a good python/OpenGL CIF renderer....   It can also import CIF files, but that seems very scary to me, and CIFs are extremely fragile.

Anyway, this CIF browser / Feff Runner seems "good enough for initial release" to me, but if you have a chance to try it out and make suggestions, that would be most welcome!

Still a work-in-progress, and there is not a "Feffit" tab on XAS Viewer yet, but it might be soon.

**Comment by maurov** [comment]
@newville for what I have tested, the "cif browser" and FEFF runner work just fine. I suggest only one (simple) extra feature: #301.

Regarding the CIF 3D rendering/visualization, I do not think it is a good idea to invest efforts on it, as there are many software out there that work just greatly and the user can use the one of choice to generate the CIF file. Rendering the 3D structure would make sense only to visualize the generated FEFF paths, but I am afraid this is not an easy task. We could build on top of [pymatgen.vis](https://pymatgen.org/pymatgen.vis.html). VTK could be integrated in Wx, but it seems there is more momentum toward WebGL.

**Comment by newville** [comment]
@maurov for structure visualization:  yes that can come later, possibly much, much later ;)
