### ISSUE TITLE
Allow short Pre-edge Range Selections

### ISSUE THREAD

**Issue by LJRH** [xraypy/xraylarch#517]
Version: Larix Larch 0.9.78
Module: xasviewer / pre_edge()
Dataset: HERFD-XANES Fe K-edge (short energy range)
Load Method: Data loaded both directly into Larch and from Athena Project

Description: On choosing a pre-edge range for a short Fe K-edge (7107 -> 7140 eV) in the xasviewer GUI will not allow a pre-edge region of less than 5 eV. Choosing a pre-edge range less than 5 eV causes a default value of pre2 to be set. Loading the dataset from an Athena project (with correct/chosen pre-edge values set), causes pre-edge values to be overwritten.

![image](https://github.com/xraypy/xraylarch/assets/29145996/2746ba98-f7f4-4e9a-bf2e-52062f8da565)

Request: For in situ HERFD-XANES datasets, it is sometimes necessary to have very short pre-edge regions which is made possible by the low noise floor in these datasets (coupled with carefully chosen longer scans to compare normalisation values with). It would be good to be able to choose short pre-edge regions of less than 5 eV in length, perhaps with a warning to the user that this could cause a normalisation issue.

Many thanks to the developers for their efforts.

L

**Comment by newville** [comment]
@LJRH thanks.  Yeah, we should handle this case better.  Maybe instead of "minimum of 5 eV" it should be "minimum of 2 data points"?

**Comment by LJRH** [comment]
Hi Matt, Yes - I think "minimum of 2 data points" is sensible, as long as it does not interfere with victoreen choice? Does the relevant code fall within pre_edge.py [182:202], is it just rounding to the nearest 5eV?

**Comment by maurov** [comment]
@LJRH this should be fixed now. Please, could check and close the issue then?

**Comment by LJRH** [comment]
> @LJRH this should be fixed now. Please, could check and close the issue then?

Thanks both. Can confirm this issue is solved in latest release.
