### ISSUE TITLE
XDI read of bad file causes seg fault

### ISSUE THREAD

**Issue by jacobfilik** [xraypy/xraylarch#519]
larch version: 0.9.74

I am writing a web application using larch and XDI files, as part of my testing I have been sending incorrectly formed XDI files to the application.

A simple file containing just:

`# XDI/1.0`

Seems to make the XDI reader seg fault taking out the interpreter.

**Comment by jacobfilik** [comment]
Once an additional line is added, i.e.

`# XDI/1.0\n#`

An error is raised but the interpreter does not crash, suggesting its possibly just single line files causing the issue, which I can easily test for outside the library.

**Comment by newville** [comment]
@jacobfilik Thanks - I can certainly believe that a single file line was not included in the test suite!  But of course, we should not be seg-faulting the interpreter when reading any file!   Will investigate...

**Comment by maurov** [comment]
@jacobfilik this should be fixed in the latest release. Please, could you test and eventually close the issue?
