### ISSUE TITLE
PCA plotter not displaying/plotting [PCA, version 0.9.78]

### ISSUE THREAD

**Issue by mrvejar** [xraypy/xraylarch#520]
Conducting a PCA with a dataset, the PCA components are plotted properly, but the components and statistics are not plotted. I was able to confirm that this issue does not occur with version 0.9.76. Also, when clicking "test current group with model" and "test selected groups with model" under the PCA tab, the fits/models do not plot either.

**Comment by newville** [comment]
@mrvejar Thanks -- this is fixed in the "master development version".  I hope to get this pushed out next week, but it might be the following week.
