### ISSUE TITLE
[Larix] Error exporting fit/statistics/components results from LCF 

### ISSUE THREAD

**Issue by MDesmau** [xraypy/xraylarch#521]
Hi,

While trying to export the results from my LCF today, I run into this error (larix/larch version 0.9.78):

Traceback (most recent call last):
  File "C:\Users\desmaum\AppData\Roaming\Python\Python311\site-packages\larch\wxxas\lincombo_panel.py", line 616, in onSaveGroupMultiFits
    write_ascii(path, header=header, label=label, _larch=_larch, *out)
TypeError: write_ascii() got an unexpected keyword argument '_larch'

I removed '_larch=_larch' from the code on my computer (local) and it looks like it's working now (creation of .dat file with the LCF data in it, with data coherent with what I saw in Larix). 

I don't know if it's a good fix for this error, but it might be worth looking into it.

Best,
Morgane

**Comment by newville** [comment]
@MDesmau Thanks for the report - I fixed that in the development branch.
