### ISSUE TITLE
Launching larch in server_mode with a specified port is broken

### ISSUE THREAD

**Issue by jacobfilik** [xraypy/xraylarch#535]
This breaks running Athena with the Larch backend.

In the run_larch() method in apps.py, I think the _action='store_true'_ flag causes the port number to be translated to True, which then is evaluated as integer 1, which is not good.

Probably an easy fix (might just want to add a specific action to the tuple describing the input args). I could try and put together a PR if it would be useful.

**Comment by newville** [comment]
@jacobfilik ah, sorry for that.  I'll try to fix this today.

**Comment by maurov** [comment]
@jacobfilik this was fixed by https://github.com/xraypy/xraylarch/commit/1eaaf9b8305b6bbc378c5fdeb7e9ee02f5cbe4dd. Please, could you check and give a feedback?

**Comment by newville** [comment]
@jacobfilik fixed.

**Comment by jacobfilik** [comment]
Thank you!
