### ISSUE TITLE
Formula question in larch.xafs.preedge

### ISSUE THREAD

**Issue by YundaoJing** [xraypy/xraylarch#537]
2  post-edge: a polynomial of order nnorm is fit to mu(energy)*energy**nvict
       between energy=[e0+norm1, e0+norm2]. nnorm, norm1, norm2 default to None,
       which will set:
         nnorm = 2 in norm2-norm1>300, 1 if norm2-norm1>30, or 0 if less.
         norm2 = max energy - e0, rounded to 5 eV
         norm1 = roughly min(150, norm2/3.0), rounded to 5 eV

The post-edge formula should be 'mu(energy)*energy**nnorm', am I right?

**Comment by newville** [comment]
@YundaoJing No, that is not correct, but the formula with "nvict" is also no longer true.  The polynomial is fit to "mu-pre_edge", where "pre_edge" is the fitted pre-edge curve (which can include nvict, but is linear when nvict=0).

I fixed the docstring.
