### ISSUE TITLE
Import Error 'get_desktop'

### ISSUE THREAD

**Issue by Daria-Boglaienko** [xraypy/xraylarch#539]
Installed Larch 0.9.81 for Windows, but can't find a way to launch it. When typing "larix" in Anaconda Prompt, getting the following error:
ImportError: cannot import name 'get_desktop' from 'pyshortcuts' (C:\Users\<username>\AppData\Local\xraylarch\Lib\site-packages\pyshortcuts\__init__.py)

**Comment by newville** [comment]
This should be fixed with `pip install --upgrade pyshortcuts`

**Comment by newville** [comment]
@Daria-Boglaienko Great, and sorry for the trouble!!
