### ISSUE TITLE
Error Saving Chi Fit Results in Larix

### ISSUE THREAD

**Issue by catalano-wustl** [xraypy/xraylarch#541]
I'm using Larix in Larch 0.9.81 for FEFF fitting. In the Feffit Results window, I am trying to save the fitting results using the File -> Save Fit options. I can save the FT mag and Real FT parts without a problem. However, I I try to save the k-weight chi fit, I get the following error and no file is written:

Traceback (most recent call last):
  File "C:\Users\catalano\xraylarch\Lib\site-packages\larch\wxxas\feffit_panel.py", line 2195, in onSaveFit
    ydata  = getattr(ds0.data, yname)[:nx] * xarr**kw
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'chikw'. Did you mean: 'chie'?

Similarly, if I try to save the unweighted k fit, nothing is written and I get the following error:

Traceback (most recent call last):
  File "C:\Users\catalano\xraylarch\Lib\site-packages\larch\wxxas\feffit_panel.py", line 2195, in onSaveFit
    ydata  = getattr(ds0.data, yname)[:nx] * xarr**kw
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'chik'. Did you mean: 'chi'?

I can't tell if this is a bug of my Larix session (it gets unstable after too much usage) or if this is an underlying bug in Larix.

**Comment by newville** [comment]
@catalano-wustl Thanks - I'll investigate.

**Comment by catalano-wustl** [comment]
I should have added there is a workaround for now: Saving the chi data and fit from the plotter window.
