### ISSUE TITLE
issue of import ICSD cif file to Feff calculations

### ISSUE THREAD

**Issue by supperpojke** [xraypy/xraylarch#542]
Hello, I found it is not able to import the CIF file from ICSD database code 6233. but it works in Athena. I try to export the .inp Feff file, then import to Larix which is not working unfortunately. 

Best regards,

Johan

Here is the information when import CIF to Larix:
---------------------------------------------------------------------------------------------------
Elements: ['Na', 'Au', 'S', 'O']
Sites: [2.26152919 6.7051275  1.40462614] Na+
Traceback (most recent calls last):
  File "C:\Apps\larch\Lib\site-packages\larch\wxlib\structure2feff_browser.py", line 414, in onImportStructure
    sites = ['%d' % (i+1) for i in range(len(sites))]
                                         ^^^^^^^^^^
TypeError: object of type 'PeriodicSite' has no len()
---------------------------------------------------------------------------------------------------

**Comment by newville** [comment]
@supperpojke Thanks and sorry for the the trouble.  Fortunately, this is example does work with larixite: 
     https://millenia.cars.aps.anl.gov/larixite/cifs/ICSD_CollCode6233.cif

(which uses the latest recommended pymatgen interface), so we'll update Larch to use this code relatively easily.

**Comment by newville** [comment]
@supperpojke should be fixed in development branch (soon to be released)
