### ISSUE TITLE
importing methods from larch into a plugin

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#80]
Save the following as `$HOME/.larch/plugins/mymod.py`

```
  from larch import use_plugin_path
  import numpy as np
  use_plugin_path('wx')
  from plotter import (_newplot, _plot)

  def someplot(_larch=None, **kws):
      x = np.linspace(0, 10, 101)
      y1 = np.sin(x)
      _newplot(x, y1)

  def registerLarchPlugin(): # must have a function with this name!
      return ('mymod', { 'someplot': someplot })
```

At the larch command line, do:

```
  larch> add_plugin('mymod')
  larch> someplot()
  file <stdin>, line 0
  AttributeError: 'NoneType' object has no attribute 'raise_exception'
      someplot()
```

The immediate problem is that importing `_newplot` as [explained the other day on the mailing list](http://www.mail-archive.com/ifeffit@millenia.cars.aps.anl.gov/msg04579.html) does not seem to work as advertised.  Or, I suppose, I am not understanding the ad copy....

The other issue is that the error message is not so helpful.  It would, I think, be more helpful to have a backtrace to the point in the code that throws the exception.  It is not even clear from the error message that the `_newplot(x,y1)` line throws the exception.  (It does.  Comment it out, no exception.)

**Comment by newville** [comment]
Plugins are now greatly discouraged...
