### ISSUE TITLE
system level plugin locations

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#93]
[The Larch document](http://xraypy.github.io/xraylarch/devel/plugins.html#locations-of-plugins) says that the system location for plugins is `/usr/local/share/larch/plugins`.  In practice, on my Ubuntu machines, plugins get installed into `/usr/share/larch/plugins`.  (I presume that is because you use `sys.prefix` in `setup.py`, which is `/usr`.)

I suppose that `/usr/local/share` is the "correct" location for data associated with a package built from source.  (Here, "correct" is relative to the confusing and often-ignored linux file system standard.)  So the request here is to modify either `setup.py` or the doc so they agree.

On a related topic, do you have a recommended link to a good `setup.py` tutorial?  I find the offical docs to be rather thin reading.  What I'd like to read is a cookbook of examples.

**Comment by newville** [comment]
This is now significantly changed.  Larch plugins are installed to the user's account ($HOME/.larch on unix or a similar %APPUSER%\larch on Windows).  This makes it much easier to manipulate post-install,  including blowing away an install.  And it means non-root installs are possible.
