### ISSUE TITLE
FeffitDataSet Group does not appear to handle epsilon_k corrrectly

### ISSUE THREAD

**Issue by bruceravel** [xraypy/xraylarch#97]
[This line](https://github.com/xraypy/xraylarch/blob/master/plugins/xafs/feffit.py#L198) looks wrong to me.  Shouldn't it be 

```python
if isinstance(self.data.epsilon_k, np.darray):
```

**Comment by newville** [comment]
Yep. will fix.

**Comment by newville** [comment]
I think this may be now fixed.  I verified that I can set epsilon_k to a single value or an array.   I haven't yet tested multiple-dataset fits.
